Repository gnosis/safe-ios, pull requests merged in 2019-07, with the labels that each got.

#927 GH-905 Add WCSessionRepository with InMemoryWCSessionRepository impl
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletDomainModel/WalletConnect/WCSession.swift
  MultisigWallet/MultisigWalletDomainModel/WalletConnect/WCSessionRepository.swift
  MultisigWallet/MultisigWalletImplementations/MockRepositories/InMemoryWCSessionRepository.swift
  MultisigWallet/MultisigWalletImplementations/MockRepositories/InMemoryWCSessionRepositoryTests.swift
Labels: feature

#931 Feature/gh 917 wc lib
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnect/AES_256_CBC_HMAC_SHA256_Codec.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnect/BridgeTransport.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnect/HandshakeHandler.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnect/JSONRPC_2_0/JSONRPC_2_0.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnect/JSONRPC_2_0/JSONRPC_2_0_Tests.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnect/PubSubMessage.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnect/Serializer.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnect/Server.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnect/Session.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnect/SessionTests.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnect/UpdateSessionHandler.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnect/UpdateSessionRequest.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnect/WebSocketConnection.swift
  safe/safe.xcodeproj/project.pbxproj
  safe/safe.xcodeproj/xcshareddata/xcschemes/safe.xcscheme
  safe/safe/IntegrationTests/WalletConnectIntegrationTests.swift
Labels: feature

#936 Feature/gh 916 wallet connect domain service
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletDomainModel/WalletConnect/WCSendTransactionRequest.swift
  MultisigWallet/MultisigWalletDomainModel/WalletConnect/WCSession.swift
  MultisigWallet/MultisigWalletDomainModel/WalletConnect/WCSessionRepository.swift
  MultisigWallet/MultisigWalletDomainModel/WalletConnect/WalletConnectDomainService.swift
  MultisigWallet/MultisigWalletImplementations/MockRepositories/InMemoryWCSessionRepository.swift
  MultisigWallet/MultisigWalletImplementations/MockRepositories/InMemoryWCSessionRepositoryTests.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/AES_256_CBC_HMAC_SHA256_Codec.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/BridgeTransport.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/HandshakeHandler.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/JSONRPC_2_0/JSONRPC_2_0.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/JSONRPC_2_0/JSONRPC_2_0_Tests.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/PubSubMessage.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/Serializer.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/Server.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/Session.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/SessionTests.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/UpdateSessionHandler.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/UpdateSessionRequest.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/WebSocketConnection.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectService.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectServiceTests.swift
  safe/safe/IntegrationTests/WalletConnectIntegrationTests.swift
Labels: feature

#938 Feature/gh 918 wc application service
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/ApplicationServiceRegistry.swift
  MultisigWallet/MultisigWalletApplication/MockWalletConnectApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WCSessionData.swift
  MultisigWallet/MultisigWalletApplication/WalletConnectApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletConnectApplicationServiceTests.swift
  MultisigWallet/MultisigWalletApplication/en.lproj/Localizable.strings
  MultisigWallet/MultisigWalletDomainModel/DomainRegistry.swift
  MultisigWallet/MultisigWalletDomainModel/DomainRegistryTests.swift
  MultisigWallet/MultisigWalletDomainModel/Ethereum/EthereumNodeDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/MockEthereumNodeService1.swift
  MultisigWallet/MultisigWalletDomainModel/WalletConnect/WCSendTransactionRequest.swift
  MultisigWallet/MultisigWalletDomainModel/WalletConnect/WCSession.swift
  MultisigWallet/MultisigWalletDomainModel/WalletConnect/WCTestStubs.swift
  MultisigWallet/MultisigWalletDomainModel/WalletConnect/WalletConnectDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/WalletConnect/WalletConnectSessionRepository.swift
  MultisigWallet/MultisigWalletImplementations/MockRepositories/InMemoryWCSessionRepository.swift
  MultisigWallet/MultisigWalletImplementations/Services/DemoEthereumNodeService.swift
  MultisigWallet/MultisigWalletImplementations/Services/MockEthereumNodeService.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/Server.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectService.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectServiceTests.swift
  MultisigWallet/MultisigWalletImplementations/infura/InfuraEthereumNodeService.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/MenuTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/MenuTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/BasicTableViewCell+WCSessionData.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCMenuCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCSendReviewViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCSessionListCell.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCSessionListCell.xib
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCSessionListTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCSessionListTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WalletConnectFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WalletConnectFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WalletConnectMenuCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WalletConnectMenuCommandTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendReviewViewController.swift
  SafeUIKit/SafeAppUI/SafeTestCase.swift
  SafeUIKit/SafeAppUI/UIAlertController+Safe.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  safe/safe/MultisigWalletConfigurator.swift
Labels: feature

#943 GH-934 implemented raw call to ethereum node
  Common/Common.xcodeproj/project.pbxproj
  Common/Common/HTTPClient.swift
  Common/Common/JSONHTTPClient.swift
  MultisigWallet/MultisigWalletApplication/EthereumApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/NotificationService/MockNotificationService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
  MultisigWallet/MultisigWalletImplementations/Services/MockTransactionRelayService.swift
  MultisigWallet/MultisigWalletImplementations/infura/InfuraEthereumNodeService.swift
  safe/safe/IntegrationTests/HTTPNotificatonServiceTests.swift
  safe/safe/IntegrationTests/InfuraEthereumNodeServiceTests.swift
Labels: feature

#944 GH-911 New repository for app settings
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletDomainModel/AppSettingsRepository.swift
  MultisigWallet/MultisigWalletDomainModel/DomainRegistry.swift
  MultisigWallet/MultisigWalletDomainModel/DomainRegistryTests.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/UserDefaultsAppSettingsRepository.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/UserDefaultsAppSettingsRepositoryTests.swift
Labels: feature

#945 Feature/gh 900 walletconnect onboarding
  MultisigWallet/MultisigWalletApplication/MockWalletConnectApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletConnectApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletConnectApplicationServiceTests.swift
  SafeUIKit/SafeAppUI/FlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCOnboardingPageDataSource.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCOnboardingPageDataSourceTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCOnboardingStepViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCOnboardingStepViewController.xib
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCOnboardingStepViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCOnboardingToolbar.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCOnboardingToolbarTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCOnboardingViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCOnboardingViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCSessionListTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WalletConnectFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WalletConnectFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/UIViewController+Back.swift
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/wallet-connect/1.imageset/1.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/wallet-connect/1.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/wallet-connect/2.imageset/2.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/wallet-connect/2.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/wallet-connect/3.imageset/3.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/wallet-connect/3.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/wallet-connect/Contents.json
  SafeUIKit/SafeAppUI/TestFlowCoordinator.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeAppUI/generated/Assets.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Components/ScanBarButtonItem/ScanBarButtonItem.swift
  safe/safe/MultisigWalletConfigurator.swift
Labels: feature

#946 Feature/gh 904 deeplinks
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCOnboardingViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCSessionListTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCSessionListTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WalletConnectFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WalletConnectFlowCoordinatorTests.swift
  safe/safe.xcodeproj/project.pbxproj
  safe/safe/AppDelegate.swift
  safe/safe/AppDelegateTests.swift
  safe/safe/Info.plist
Labels: feature

#954 GH-606 updated the field
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/ConnectBrowserExtensionDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/ReplaceBrowserExtensionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/ReplaceBrowserExtensionDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/TransactionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/Wallet.swift
Labels: improvement

#953 Feature/gh 570 build first time
  .env.default.example
  AppConfig.example.yml
  GoogleService-Info.example.plist
  README.md
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/AddressInputViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/RecoveryPhraseInputViewController.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
Labels: maintenance

#952 GH-895 updated localizations
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/AddressInputViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/RecoveryPhraseInputViewController.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
Labels: bug

#948 GH-897 fixed
  MultisigWallet/MultisigWalletApplication/EventRelay.swift
Labels: bug

#949 Feature/gh 930 fix crash
  MultisigWallet/MultisigWalletApplication/MockEthereumApplicationService.swift
  SafeUIKit/SafeAppUI/MainFlow/CustomNavigationController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/OnboardingCreationFeeViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/ConfirmMnemonicViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/ConfirmMnemonicViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/FeePaidViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverRecoveryFeeViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/SuccessViewController.swift
Labels: bug

#947 GH-926 added guards for states during repeater steps
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/Wallet.swift
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
Labels: bug

#950 GH-935
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceError.swift
  MultisigWallet/MultisigWalletDomainModel/NotificationService/Messaging/CommunicationDomainService.swift
  SafeUIKit/SafeAppUI/ErrorHandler.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
Labels: bug

#951 Feature/gh 906 handle incoming requests
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/WCPendingTransactionsRepository.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/SendTransactionTests.swift
  MultisigWallet/MultisigWalletApplication/WalletConnectApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletConnectApplicationServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/BigInt+Hex.swift
  MultisigWallet/MultisigWalletDomainModel/BigInt+HexTests.swift
  MultisigWallet/MultisigWalletDomainModel/NotificationService/Messaging/SendTransactionMessage.swift
  MultisigWallet/MultisigWalletDomainModel/Transaction/Transaction.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/TransactionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/WalletConnect/WCSendTransactionRequest.swift
  MultisigWallet/MultisigWalletDomainModel/WalletConnect/WCSession.swift
  MultisigWallet/MultisigWalletDomainModel/WalletConnect/WCTestStubs.swift
  MultisigWallet/MultisigWalletDomainModel/WalletConnect/WalletConnectSessionRepository.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/Server.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectService.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectServiceTests.swift
  SafeUIKit/SafeAppUI/MainFlow/IncomingTransactionFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/IncomingTransactionsManager.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/BasicTableViewCell+WCSessionData.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCSendReviewViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WalletConnectFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendReviewViewController.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
  safe/safe/AppDelegate.swift
  safe/safe/MultisigWalletConfigurator.swift
Labels: feature

#957 GH-956 added sorting by date
  MultisigWallet/MultisigWalletImplementations/Repositories/DBTransactionRepository.swift
Labels: bug

#966 Feature/gh 962 address format
  AppConfig.example.yml
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
  encrypted_files.tar.enc
  safe/safe/AppConfig.swift
  safe/safe/MultisigWalletConfigurator.swift
Labels: bug

#967 GH-961 added rejection feature
  MultisigWallet/MultisigWalletApplication/WalletConnectApplicationService.swift
  SafeUIKit/SafeAppUI/MainFlow/IncomingTransactionFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/IncomingTransactionsManager.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCSendReviewViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransactionViewController.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
Labels: feature

#970 GH-963 GH-969 GH-963 send transaction improved
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendReviewViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransactionViewController.swift
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
Labels: bug, improvement

#971 GH-959 created placeholder
  MultisigWallet/MultisigWalletApplication/WCSessionData.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/PlaceholderCreator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCSessionListCell.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
Labels: feature

#973 GH-972 bump version
  CHANGELOG.rst
  safe/remoteNotificationHandler/Info.plist
  safe/safe/Info.plist
  safe/safe/Tests-Info.plist
  safe/safeUITests/Info.plist
Labels: maintenance

#975 Feature/gh 974 success screen
  SafeUIKit/SafeAppUI/MainFlow/IncomingTransactionFlowCoordinator.swift
Labels: improvement

#979 GH-976 normalize from and to addresses
  MultisigWallet/MultisigWalletDomainModel/WalletConnect/WCSendTransactionRequest.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/WebSocketConnection.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectServiceTests.swift
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
  safe/IdentityAccessImplementationsResources.bundle/_CodeSignature/CodeDirectory
  safe/IdentityAccessImplementationsResources.bundle/_CodeSignature/CodeRequirements-1
Labels: bug

#996 Release/1.4.0
  CHANGELOG.rst
  MultisigWallet/MultisigWalletDomainModel/WalletConnect/WCSendTransactionRequest.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/WebSocketConnection.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectServiceTests.swift
  SafeUIKit/SafeAppUI/MainFlow/IncomingTransactionFlowCoordinator.swift
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
  safe/IdentityAccessImplementationsResources.bundle/_CodeSignature/CodeDirectory
  safe/IdentityAccessImplementationsResources.bundle/_CodeSignature/CodeRequirements-1
  safe/remoteNotificationHandler/Info.plist
  safe/safe/Info.plist
  safe/safe/Tests-Info.plist
  safe/safeUITests/Info.plist
Labels: maintenance

#1010 Feature/gh 984 thread safety
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/BridgeTransport.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/JSONRPC_2_0/JSONRPC_2_0.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/JSONRPC_2_0/JSONRPC_2_0_Tests.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/Server.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/WebSocketConnection.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectService.swift
Labels: bug

#1011 GH-984 added preconditions for queue context
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/BridgeTransport.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/Server.swift
Labels: bug

#1013 Release/1.4.0
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/BridgeTransport.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/JSONRPC_2_0/JSONRPC_2_0.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/JSONRPC_2_0/JSONRPC_2_0_Tests.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/Server.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectLib/WebSocketConnection.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectService.swift
Labels: maintenance

#1014 GH-992 updated icons
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/ReplaceBrowserExtensionFlowCoordinator.swift
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/connect-browser-extension/connect-intro-icon.imageset/connectBrowserWithPhone.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/replace-browser-extension/in-progress-icon.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/replace-browser-extension/in-progress-icon.imageset/browserExtensionInProgress.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/replace-browser-extension/intro-icon.imageset/intro.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/replace-browser-extension/intro-icon.imageset/replaceBrowserExtension.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/replacePhrase.imageset/replacePhrase.pdf
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeAppUI/generated/Assets.swift
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/settings.imageset/settings.pdf
Labels: improvement

#1019 GH-994 wallet connect new onbording assets
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/wallet-connect/1.imageset/1.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/wallet-connect/1.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/wallet-connect/1.imageset/onboarding1.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/wallet-connect/2.imageset/2.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/wallet-connect/2.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/wallet-connect/2.imageset/onboarding2.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/wallet-connect/3.imageset/3.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/wallet-connect/3.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/wallet-connect/3.imageset/onboarding3.pdf
Labels: feature

#1032 GH-1021 Added overlay with custom transition
  SafeUIKit/Colors.txt
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/MasterPassword.storyboard
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/OnboardingTermsViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/OverlayTransitionAnimator.swift
  SafeUIKit/SafeAppUI/generated/Assets.swift
  SafeUIKit/SafeAppUI/generated/Colors.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/generated/Assets.swift
  SafeUIKit/SafeUIKit/generated/Colors.swift
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
Labels: improvement
