Repository gnosis/safe-ios, pull requests merged in 2019-10, with the labels that each got.

#1183 Feature/gh 1096 pushes
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  SafeUIKit/SafeAppUI/MainFlow/IncomingTransactionFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/SwitchSafesFlowCoordinator.swift
Labels: feature

#1185 Feature/gh 1091 edit safe name
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/Wallet.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/DBWalletRepository.swift
  SafeUIKit/SafeAppUI/MainFlow/Main.storyboard
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/MainViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ChangePassword/VerifyCurrentPasswordViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/EditSafeName/EditSafeNameCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/EditSafeName/EditSafeNameViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/MenuTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/RemoveSafe/RemoveSafeIntroViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/MenuTrackingEvent.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/OnboardingCreationFeeViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverRecoveryFeeViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/ReceiveFunds/ReceiveFundsViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/TransactionDetails/TransactionDetailsViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/CardViewController/AddressDetailView.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/CardViewController/AddressDetailView.xib
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Components/TextInputs/VerifiableInput/VerifiableInput.swift
  safe/safe.xcodeproj/project.pbxproj
  safe/safe/Migrations/M0007_RemoveDiscardedTransactionState.swift
  safe/safe/Migrations/M0008_AddWalletNameField.swift
  safe/safe/Migrations/Migrations.swift
Labels: feature

#1186 Feature/gh 1096 notification service
  MultisigWallet/CommonTests/WCTestStubs.swift
  MultisigWallet/MultisigWalletApplication/RecoveryApplicationService.swift
  MultisigWallet/MultisigWalletApplication/TransactionData.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletConnectApplicationService.swift
  MultisigWallet/MultisigWalletApplication/mocks/MockWalletApplicationService.swift
  MultisigWallet/MultisigWalletApplicationTests/WalletApplicationServiceTests/BaseWalletApplicationServiceTests.swift
  MultisigWallet/MultisigWalletApplicationTests/WalletApplicationServiceTests/SendTransactionTests.swift
  MultisigWallet/MultisigWalletApplicationTests/WalletApplicationServiceTests/TokenListItemApplicationTests.swift
  MultisigWallet/MultisigWalletApplicationTests/WalletConnectApplicationServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Account/AccountUpdateDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Account/MockAccountUpdateService.swift
  MultisigWallet/MultisigWalletDomainModel/Transaction/Transaction.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/WalletDomainService.swift
  MultisigWallet/MultisigWalletDomainModelTests/AccountUpdateDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModelTests/TransactionTests.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/TransactionView/TransactionViewViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/SwitchSafesFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/OnboardingCreationFeeViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/OnboardingFeePaidViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverRecoveryFeeViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewModel.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendReviewViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/TransactionDetails/TransactionDetailsViewControllerTests.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransactionViewController.swift
  SafeUIKit/SafeAppUI/TestExtensions.swift
Labels: feature

#1188 GH-1096 Memory leaks fixed; incoming txes behavior
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletConnectApplicationService.swift
  MultisigWallet/MultisigWalletApplication/mocks/MockWalletApplicationService.swift
  MultisigWallet/MultisigWalletApplicationTests/WalletConnectApplicationServiceTests.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectService.swift
  SafeUIKit/SafeAppUI/MainFlow/IncomingTransactionFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/MainViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/EditSafeName/EditSafeNameViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/MenuTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCSessionListTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WalletConnectFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WalletConnectFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WalletConnectMenuCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/ReceiveFunds/ReceiveFundsViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/TransactionDetails/TransactionDetailsViewController.swift
Labels: feature

#1189 GH-1096 fixed some
  MultisigWallet/MultisigWalletApplication/EventRelay.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/mocks/MockWalletApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/Account/Account.swift
  MultisigWallet/MultisigWalletDomainModel/Account/AccountUpdateDomainService.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/RemoveSafe/RemoveSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/SwitchSafesFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/AddressInputViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/BaseInputViewController.swift
  SafeUIKit/SafeUIKit/Components/AddressInput/AddressInput.swift
  SafeUIKit/SafeUIKit/Components/IdenticonView/IdenticonView.swift
Labels: improvement

#1191 GH-1190 updated
  CHANGELOG.rst
  safe/remoteNotificationHandler/Info.plist
  safe/safe/Info.plist
  safe/safe/Tests-Info.plist
  safe/safeUITests/Info.plist
Labels: maintenance

#1210 GH-1197 added new screen
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinatorAppTests.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/MainTrackingEvents.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookEntry.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookEntryTableViewCell.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookEntryTableViewCell.xib
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookMenuCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/MenuTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/MenuTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/Unlock/UnlockViewControllerTests.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
Labels: feature

#1211 GH-1199 view entry screen
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/MainTrackingEvents.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookEntryViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookFlowCoordinator.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
Labels: feature

#1213 Feature/gh 1202 address input
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/AddressInputViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewController.swift
  SafeUIKit/SafeUIKit/Components/AddressInput/AddressInput.swift
  SafeUIKit/SafeUIKit/Components/AddressInput/AddressInputTests.swift
  SafeUIKit/SafeUIKit/Components/EthereumAddressLabel/EthereumAddressLabel.swift
  SafeUIKit/SafeUIKit/Components/EthereumAddressLabel/FullEthereumAddressLabel.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/VerifiableInput/VerifiableInput.swift
  SafeUIKit/SafeUIKit/Components/TransferView/TransferView.swift
  SafeUIKit/SafeUIKit/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKitDemo/DetailControllers/AddressInputViewController.swift
  SafeUIKit/SafeUIKitDemo/DetailControllers/TransferViewViewController.swift
Labels: feature

#1214 GH-1200 edit screen
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/MainTrackingEvents.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookEditEntryViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookEditEntryViewController.xib
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookFlowCoordinator.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Components/AddressInput/AddressInput.swift
Labels: feature

#1215 GH-1201 new entry screen
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/MainTrackingEvents.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookEditEntryViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookFlowCoordinator.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
Labels: feature

#1219 Feature/gh 1206 address book framework
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletDomainModel/AddressBook/AddressBookEntry.swift
  MultisigWallet/MultisigWalletDomainModel/AddressBook/AddressBookRepository.swift
  MultisigWallet/MultisigWalletDomainModel/DomainRegistry.swift
  MultisigWallet/MultisigWalletImplementations/MockRepositories/InMemoryAddressBookRepository.swift
  MultisigWallet/MultisigWalletImplementations/MockRepositories/InMemoryWCSessionRepository.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/DBAddressBookRepository.swift
  MultisigWallet/MultisigWalletImplementationsTests/DBAddressBookRepositoryTests.swift
  safe/safe/MultisigWalletConfigurator.swift
Labels: feature

#1216 GH-1198 picker
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/AddressInputViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewController.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
Labels: feature

#1220 GH-1202 add addressName func to the WalletApplicationService
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/mocks/MockWalletApplicationService.swift
  MultisigWallet/MultisigWalletImplementations/Services/Keycard/KeycardInitializer.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/AddressInputViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewController.swift
Labels: feature

#1221 GH-1205 added address labels to the transaction view
  MultisigWallet/MultisigWalletApplication/RecoveryApplicationService.swift
  MultisigWallet/MultisigWalletApplication/TransactionData.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/mocks/MockWalletApplicationService.swift
  MultisigWallet/MultisigWalletApplicationTests/WalletApplicationServiceTests/BaseWalletApplicationServiceTests.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/TransactionView/TransactionTableViewCell.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/TransactionView/TransactionViewViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/TransactionDetails/TransactionDetailsViewControllerTests.swift
  SafeUIKit/SafeAppUI/TestExtensions.swift
  SafeUIKit/SafeUIKit/Components/EthereumAddressLabel/EthereumAddressLabel.swift
  SafeUIKit/SafeUIKit/Components/EthereumAddressLabel/EthereumAddressLabelTests.swift
Labels: feature

#1223 GH-1222 using actual data for address book
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/AddressBookEntryData.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/mocks/MockWalletApplicationService.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookEditEntryViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookEntry.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookEntryTableViewCell.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookEntryViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/AddressInputViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewController.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
Labels: feature

#1224 GH-1192 fixed
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransactionViewController.swift
  safe.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: bug

#1225 GH-1218 instant switch
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/SwitchSafesTableViewController.swift
Labels: improvement

#1226 GH-1212 crash fix
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/MainViewController.swift
Labels: bug

#1228 Feature/gh 1204 transfer view adjustments
  Common/CommonImplementations/DBAbstractRepository.swift
  Common/CommonImplementations/TableSchema.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/DBAddressBookRepository.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/DBTokeListItemRepository.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/AssetView/AssetViewViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/MainViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/MainViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendReviewViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/TransactionDetails/TransactionDetailsViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/TransactionDetails/TransactionDetailsViewControllerTests.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit/Components/FeedbackTooltip/FeedbackTooltip.swift
  SafeUIKit/SafeUIKit/Components/TransferView/TransferView.swift
  SafeUIKit/SafeUIKit/Components/TransferView/TransferView.xib
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/transfer-view/threeDotsDark.imageset/Contents.json
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/transfer-view/threeDotsDark.imageset/threeDotsDark.pdf
  SafeUIKit/SafeUIKit/generated/Assets.swift
  SafeUIKit/SafeUIKitDemo/Main/SendInputDemoViewController.swift
Labels: feature

#1235 GH-1229 keep selection
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/BaseAddSafeCommand.swift
  safe.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: bug

#1241 Feature/gh 1239 add token get in touch
  SafeUIKit/SafeAppUI/MainFlow/Menu/GetInTouch/GetInTouchTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Tokens/ManageTokens/AddToken/AddTokenTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Tokens/ManageTokens/AddToken/AddTokenTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Tokens/ManageTokens/AddToken/MissingTokenFooterView.swift
  SafeUIKit/SafeAppUI/MainFlow/Tokens/ManageTokens/AddToken/MissingTokenFooterView.xib
  SafeUIKit/SafeAppUI/MainFlow/Tokens/ManageTokens/AddToken/NoResultsForAddTokenView.swift
  SafeUIKit/SafeAppUI/MainFlow/Tokens/ManageTokens/AddToken/NoResultsForAddTokenView.xib
  SafeUIKit/SafeAppUI/MainFlow/UIBarButtonItem+Items.swift
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/add-token-get-in-touch.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/add-token-get-in-touch.imageset/group.pdf
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeAppUI/generated/Assets.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
Labels: feature

#1242 Feature/gh 1232 tooltip
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/TransactionView/TransactionViewViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Tokens/ManageTokens/ManageTokensTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/TransactionDetails/TransactionDetailsViewController.swift
  SafeUIKit/SafeAppUI/TooltipControlCenter.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Components/FeeCalculation/FeeCalculationAssetLine.swift
  SafeUIKit/SafeUIKit/Components/FeedbackTooltip/FeedbackTooltip.swift
  SafeUIKit/SafeUIKit/Components/TransferView/TransferView.swift
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/tooltip/Contents.json
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/tooltip/Green_Tooltip_Arrow.imageset/Contents.json
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/tooltip/Green_Tooltip_Arrow.imageset/Green_Tooltip_Arrow.pdf
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/tooltip/Green_Tooltip_Background.imageset/Contents.json
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/tooltip/Green_Tooltip_Background.imageset/Green_Tooltip_Background.pdf
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/tooltip/Green_Tooltip_Cross.imageset/Contents.json
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/tooltip/Green_Tooltip_Cross.imageset/Green_Tooltip_Cross.pdf
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/tooltip/White_Tooltip_Background.imageset/Contents.json
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/tooltip/White_Tooltip_Background.imageset/White_Tooltip_Background.pdf
  SafeUIKit/SafeUIKit/generated/Assets.swift
Labels: feature

#1246 Feature/gh 1240 safe name in address book
  Common/CommonImplementations/DBMigrationService.swift
  MultisigWallet/MultisigWalletApplication/AddressBookEntryData.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/AddressBook/AddressBookEntry.swift
  MultisigWallet/MultisigWalletDomainModel/AddressBook/AddressBookRepository.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/Wallet.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/WalletDomainService.swift
  MultisigWallet/MultisigWalletDomainModelTests/BaseDeploymentDomainServiceTests.swift
  MultisigWallet/MultisigWalletImplementations/MockRepositories/InMemoryAddressBookRepository.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/DBAddressBookRepository.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/DBWalletRepository.swift
  MultisigWallet/MultisigWalletImplementationsTests/DBAddressBookRepositoryTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookEditEntryViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/SwitchSafesTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/AddressInputViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewController.swift
  SafeUIKit/SafeUIKit/Components/AddressInput/AddressInput.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/TextInput/TextInput.swift
  safe/safe.xcodeproj/project.pbxproj
  safe/safe/Migrations/M0009_MigrateSafesNamesToAddressBook.swift
  safe/safe/Migrations/Migrations.swift
Labels: feature

#1247 GH-1230 serialization fixed
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletDomainModel/Account/AccountUpdateDomainService.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/DBSerializable/WalletIDList+DBSerializable.swift
  MultisigWallet/MultisigWalletImplementationsTests/WalletIDListTests.swift
Labels: bug

#1248 GH-1230 Changed style
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/ConfirmMnemonicViewController.swift
Labels: bug
