Repository gnosis/safe-ios, pull requests merged in 2019-06, with the labels that each got.

#823 Feature/gh 822 part1
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/ApplicationServiceRegistry.swift
  MultisigWallet/MultisigWalletApplication/ReplaceRecoveryPhraseApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletSettingsApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/DomainRegistry.swift
  MultisigWallet/MultisigWalletDomainModel/Ethereum/ExternallyOwnedAccount.swift
  MultisigWallet/MultisigWalletDomainModel/MultiSendContractProxy.swift
  MultisigWallet/MultisigWalletDomainModel/MultiSendContractProxyTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ReplaceRecoveryPhraseDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/Wallet.swift
  MultisigWallet/MultisigWalletImplementations/Services/SynchronisationService.swift
  SafeUIKit/SafeAppUI/MainFlow/CommonTransactionViews/HorizontalSeparatorView.swift
  SafeUIKit/SafeAppUI/MainFlow/Main.storyboard
  SafeUIKit/SafeAppUI/MainFlow/Menu/MenuTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceRecoveryPhrase/ReplaceRecoveryPhraseCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceRecoveryPhrase/ReplaceRecoveryPhraseFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceRecoveryPhrase/ReplaceRecoveryPhraseReviewTransactionViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceRecoveryPhrase/ReplaceRecoveryPhraseReviewTransactionViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceRecoveryPhrase/ReplaceRecoveryPhraseViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceRecoveryPhrase/ReplaceRecoveryPhraseViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/TransactionDetails/StatusTransactionParameterView.swift
  SafeUIKit/SafeAppUI/MainFlow/TransactionDetails/TokenAmountTransactionParameterView.swift
  SafeUIKit/SafeAppUI/MainFlow/TransactionDetails/TransactionDetailsViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/TransactionDetails/TransactionDetailsViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/TransactionDetails/TransactionParameterView.swift
  SafeUIKit/SafeAppUI/generated/Sotryboards.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Components/InfoLabel/InfoLabel.swift
  SafeUIKit/SafeUIKit/Components/TransferView/SettingsTransactionHeaderView.swift
  SafeUIKit/SafeUIKit/Components/TransferView/SettingsTransactionHeaderView.xib
  SafeUIKit/SafeUIKit/Components/TransferView/TransferView.swift
  SafeUIKit/SafeUIKit/Components/TransferView/TransferView.xib
  safe/safe/AppDelegate.swift
  safe/safe/MultisigWalletConfigurator.swift
Labels: improvement

#829 Feature/gh 828 release update
  CHANGELOG.rst
  SafeUIKit/SafeAppUI/MainFlow/TransactionDetails/TransactionDetailsViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/TransactionDetails/TransactionDetailsViewControllerTests.swift
  safe/remoteNotificationHandler/Info.plist
  safe/safe/Info.plist
  safe/safe/Tests-Info.plist
  safe/safeUITests/Info.plist
Labels: maintenance

#835 Feature/gh 828 fixes
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/SegmentBar.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverSafe.storyboard
  SafeUIKit/SafeAppUI/MainFlow/Send/FeeCalculationAssetLine+TokenData.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Tokens/BasicTableViewCell+TokenData.swift
  SafeUIKit/SafeAppUI/MainFlow/TransactionDetails/TransactionDetailsViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/CardViewController/FeeRequestView.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/RecoveryPhraseInputViewController.swift
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/segment-bar/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/segment-bar/left.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/segment-bar/left.imageset/left.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/segment-bar/middle.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/segment-bar/middle.imageset/middle.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/segment-bar/right.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/segment-bar/right.imageset/right.pdf
  SafeUIKit/SafeAppUI/generated/Assets.swift
  SafeUIKit/SafeUIKit/AccountBalanceView.swift
  SafeUIKit/SafeUIKit/Components/AmountLabel/AmountLabel.swift
  SafeUIKit/SafeUIKit/Components/StandardButton/StandardButton.swift
  SafeUIKit/SafeUIKit/Components/TransferView/TransferView.swift
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
Labels: bug

#836 Release/1.3.0
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/SegmentBar.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverSafe.storyboard
  SafeUIKit/SafeAppUI/MainFlow/Send/FeeCalculationAssetLine+TokenData.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Tokens/BasicTableViewCell+TokenData.swift
  SafeUIKit/SafeAppUI/MainFlow/TransactionDetails/TransactionDetailsViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/CardViewController/FeeRequestView.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/RecoveryPhraseInputViewController.swift
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/segment-bar/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/segment-bar/left.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/segment-bar/left.imageset/left.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/segment-bar/middle.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/segment-bar/middle.imageset/middle.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/segment-bar/right.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/segment-bar/right.imageset/right.pdf
  SafeUIKit/SafeAppUI/generated/Assets.swift
  SafeUIKit/SafeUIKit/AccountBalanceView.swift
  SafeUIKit/SafeUIKit/Components/AmountLabel/AmountLabel.swift
  SafeUIKit/SafeUIKit/Components/StandardButton/StandardButton.swift
  SafeUIKit/SafeUIKit/Components/TransferView/TransferView.swift
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
Labels: maintenance

#839 GH-837 updated the order of fields in sql
  MultisigWallet/MultisigWalletDomainModel/Wallet/TransactionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/TransactionDomainServiceTests.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/DBTokeListItemRepository.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/DBWalletRepository.swift
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
  safe/safe/MultisigWalletConfigurator.swift
Labels: bug

#843 Feature/gh 842 part1
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/EstimateSafeCreationRequest.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/GetSafeCreationStatusRequest.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/MultiTokenEstimateTransactionRequest.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/SafeCreationRequest.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/StringifiedBigInt.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/StringifiedBigIntTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/SafeCreationResponseValidator.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/SafeCreationResponseValidatorTests.swift
  MultisigWallet/MultisigWalletImplementations/Services/HTTPGnosisTransactionRelayService.swift
  encrypted_files.tar.enc
  safe/safe/IntegrationTests/HTTPGnosisTransactionRelayServiceTests.swift
Labels: bug

#844 Feature/gh 842 part2
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/MockWalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/RecoveryApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/WalletApplicationServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Account/AccountUpdateDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/NotificationService/Messaging/SendTransactionMessage.swift
  MultisigWallet/MultisigWalletDomainModel/Transaction/Transaction.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/EstimateTransactionRequest.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/GetSafeInfoRequest.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/StringifiedBigInt.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/TransactionRelayDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/ReplaceBrowserExtensionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/ReplaceBrowserExtensionDomainServiceBaseTestCase.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/MockTransactionRelayService1.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/DBTransactionRepository.swift
  MultisigWallet/MultisigWalletImplementations/Services/EncryptionServiceTests.swift
  MultisigWallet/MultisigWalletImplementations/Services/HTTPGnosisTransactionRelayService.swift
  MultisigWallet/MultisigWalletImplementations/Services/MockTransactionRelayService.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/TransactionView/TransactionViewViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreationFeeIntro/OnboardingPaymentMethodViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/OnboardingCreationFeeViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverRecoveryFeeViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewModel.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransactionViewController.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Components/FeeCalculationCell/FeeCalculationCell.swift
  SafeUIKit/SafeUIKit/Components/TransactionFeeView/TransactionFeeCell.swift
  SafeUIKit/SafeUIKit/Components/TransactionFeeView/TransactionFeeCellTests.swift
  SafeUIKit/SafeUIKit/Components/TransactionFeeView/TransactionFeeView.swift
  SafeUIKit/SafeUIKit/Components/TransactionFeeView/TransactionFeeViewTests.swift
  SafeUIKit/SafeUIKit/TokenNumberFormatter.swift
  SafeUIKit/SafeUIKit/TokenNumberFormatterTests.swift
  SafeUIKit/SafeUIKit/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKitDemo/DetailControllers/TransactionFeeViewViewController.swift
  SafeUIKit/SafeUIKitDemo/Main/Main.storyboard
  encrypted_files.tar.enc
  safe/safe.xcodeproj/project.pbxproj
  safe/safe/IntegrationTests/Safe.swift
  safe/safe/Migrations/M0005_ChangeTransactionFeeColumnType.swift
  safe/safe/Migrations/Migrations.swift
Labels: bug

#847 Feature/gh 846 error domain skip
  MultisigWallet/MultisigWalletImplementations/Services/SynchronisationService.swift
Labels: bug

#849 GH-816 replaced forced unwrap with errors
  MultisigWallet/MultisigWalletDomainModel/Wallet/TransactionDomainService.swift
Labels: bug

#850 GH-650 always show back button on review screen
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransactionViewController.swift
Labels: bug

#852 GH-848 handling biometry failures now
  IdentityAccess/IdentityAccessApplication/AuthenticationApplicationService.swift
  IdentityAccess/IdentityAccessApplication/AuthenticationApplicationServiceTests.swift
  IdentityAccess/IdentityAccessDomainModel/Gatekeeper/SingleGatekeeperRepository.swift
  IdentityAccess/IdentityAccessDomainModel/IdentityService/BiometricAuthenticationService.swift
  IdentityAccess/IdentityAccessDomainModel/IdentityService/IdentityService.swift
  IdentityAccess/IdentityAccessDomainModel/IdentityService/IdentityServiceTests.swift
  IdentityAccess/IdentityAccessDomainModel/User/SingleUserRepository.swift
  IdentityAccess/IdentityAccessImplementations/biometry/BiometricService.swift
  IdentityAccess/IdentityAccessImplementations/biometry/BiometricServiceTests.swift
  IdentityAccess/IdentityAccessImplementations/persistence/SingleGatekeeperRepository/InMemoryGatekeeperRepository.swift
  IdentityAccess/IdentityAccessImplementations/persistence/SingleGatekeeperRepository/InMemoryGatekeeperRepositoryTests.swift
  IdentityAccess/IdentityAccessImplementations/persistence/SingleUserRepository/DBSingleUserRepository.swift
  IdentityAccess/IdentityAccessImplementations/persistence/SingleUserRepository/DBSingleUserRepositoryIntegrationTests.swift
  IdentityAccess/IdentityAccessImplementations/persistence/SingleUserRepository/DBSingleUserRepositoryTests.swift
  IdentityAccess/IdentityAccessImplementations/persistence/SingleUserRepository/InMemoryUserRepository.swift
  IdentityAccess/IdentityAccessImplementations/persistence/SingleUserRepository/InMemoryUserRepositoryTests.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/Unlock/UnlockViewController.swift
  safe/safe/IdentityAccessConfigurator.swift
Labels: bug

#853 Feature/gh 678 change password
  IdentityAccess/IdentityAccessApplication/AuthenticationApplicationService.swift
  IdentityAccess/IdentityAccessDomainModel/IdentityService/IdentityService.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ChangePassword/ChangePassword.storyboard
  SafeUIKit/SafeAppUI/MainFlow/Menu/ChangePassword/VerifyCurrentPasswordViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ChangePassword/VerifyCurrentPasswordViewControllerTests.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Components/TextInputs/VerifiableInput/VerifiableInput.swift
Labels: improvement

#854 GH-729 removed walletID field
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/BaseWalletApplicationServiceTests.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/SendTransactionTests.swift
  MultisigWallet/MultisigWalletDomainModel/Transaction/Transaction.swift
  MultisigWallet/MultisigWalletDomainModel/Transaction/TransactionRepository.swift
  MultisigWallet/MultisigWalletDomainModel/Transaction/TransactionTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/DisconnectBrowserExtensionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/DisconnectBrowserExtensionDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/ReplaceBrowserExtensionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/ReplaceBrowserExtensionDomainServicePostProcessingTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/ReplaceBrowserExtensionDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ReplaceRecoveryPhraseDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/TransactionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/TransactionDomainServiceTests.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/DBTransactionRepository.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/DBTransactionRepositoryTests.swift
  MultisigWallet/MultisigWalletImplementations/Services/EncryptionService.swift
  MultisigWallet/MultisigWalletImplementations/Services/EncryptionServiceTests.swift
  safe/safe.xcodeproj/project.pbxproj
  safe/safe/IntegrationTests/HTTPNotificatonServiceTests.swift
  safe/safe/IntegrationTests/Safe.swift
  safe/safe/Migrations/M0006_RemoveWalletIDFromTransactions.swift
  safe/safe/Migrations/Migrations.swift
Labels: improvement

#857 Release/1.3.0
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/MockWalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/RecoveryApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/WalletApplicationServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Account/AccountUpdateDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/NotificationService/Messaging/SendTransactionMessage.swift
  MultisigWallet/MultisigWalletDomainModel/Transaction/Transaction.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/EstimateSafeCreationRequest.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/EstimateTransactionRequest.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/GetSafeCreationStatusRequest.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/GetSafeInfoRequest.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/MultiTokenEstimateTransactionRequest.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/SafeCreationRequest.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/StringifiedBigInt.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/StringifiedBigIntTests.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/TransactionRelayDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/ReplaceBrowserExtensionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/ReplaceBrowserExtensionDomainServiceBaseTestCase.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/MockTransactionRelayService1.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/SafeCreationResponseValidator.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/SafeCreationResponseValidatorTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/TransactionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/TransactionDomainServiceTests.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/DBTokeListItemRepository.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/DBTransactionRepository.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/DBWalletRepository.swift
  MultisigWallet/MultisigWalletImplementations/Services/EncryptionServiceTests.swift
  MultisigWallet/MultisigWalletImplementations/Services/HTTPGnosisTransactionRelayService.swift
  MultisigWallet/MultisigWalletImplementations/Services/MockTransactionRelayService.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/TransactionView/TransactionViewViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreationFeeIntro/OnboardingPaymentMethodViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/OnboardingCreationFeeViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverRecoveryFeeViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewModel.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransactionViewController.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Components/FeeCalculationCell/FeeCalculationCell.swift
  SafeUIKit/SafeUIKit/Components/TransactionFeeView/TransactionFeeCell.swift
  SafeUIKit/SafeUIKit/Components/TransactionFeeView/TransactionFeeCellTests.swift
  SafeUIKit/SafeUIKit/Components/TransactionFeeView/TransactionFeeView.swift
  SafeUIKit/SafeUIKit/Components/TransactionFeeView/TransactionFeeViewTests.swift
  SafeUIKit/SafeUIKit/TokenNumberFormatter.swift
  SafeUIKit/SafeUIKit/TokenNumberFormatterTests.swift
  SafeUIKit/SafeUIKit/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKitDemo/DetailControllers/TransactionFeeViewViewController.swift
  SafeUIKit/SafeUIKitDemo/Main/Main.storyboard
  encrypted_files.tar.enc
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
  safe/safe.xcodeproj/project.pbxproj
  safe/safe/IntegrationTests/HTTPGnosisTransactionRelayServiceTests.swift
  safe/safe/IntegrationTests/Safe.swift
  safe/safe/Migrations/M0005_ChangeTransactionFeeColumnType.swift
  safe/safe/Migrations/Migrations.swift
  safe/safe/MultisigWalletConfigurator.swift
Labels: maintenance

#861 GH-858 adjusted private key loading
  MultisigWallet/MultisigWalletImplementations/Services/EncryptionService.swift
Labels: bug

#859 Feature/gh 717 back gesture
  SafeUIKit/SafeAppUI/MainFlow/CustomNavigationController.swift
  SafeUIKit/SafeAppUI/MainFlow/Tokens/ManageTokens/ManageTokensFlowCoordinator.swift
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
Labels: bug

#866 Fature/gh 753
  Common/Common/JSONHTTPClient.swift
  MultisigWallet/MultisigWalletApplication/EthereumApplicationService.swift
  MultisigWallet/MultisigWalletImplementations/Services/HTTPGnosisTransactionRelayService.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/MainViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/MainViewControllerTests.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/UIApplication+Extensions.swift
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
Labels: bug

#867 Feature/gh 851
  Common/Common/TokenData.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/RBEIntroViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/RBEIntroViewControllerReadyStateTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/RBEReviewTransactionViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverRecoveryFeeViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/FeeCalculationAssetLine+TokenData.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SameTransferAndPaymentTokensFeeCalculation.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewModel.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewModelTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendReviewViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendReviewViewControllerTests.swift
Labels: bug

#868 Feature/gh 815
  Common/Common.xcodeproj/project.pbxproj
  Common/CommonImplementations/Logger/CrashlyticsLogger.swift
  Common/CommonImplementations/Tracker/CrashlyticsTrackingHandler.swift
  Common/CommonImplementations/logger/ConsoleLogger.swift
  Common/CommonImplementations/logger/ConsoleLoggerTests.swift
  Common/CommonImplementations/logger/CrashlyticsLogger.swift
  Common/CommonImplementations/logger/CrashlyticsLoggerTests.swift
  Common/CommonImplementations/logger/LogFormatter.swift
  Common/CommonImplementations/logger/LogFormatterTests.swift
  Common/CommonImplementations/logger/LogService.swift
  Common/CommonImplementations/logger/LogServiceTests.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
  safe/safe/AppDelegate.swift
Labels: bug

#865 GH-860 fix edge case when creating a new safe
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainService.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/OnboardingCreationFeeViewController.swift
Labels: bug

#870 Feautre/gh 780 system failure
  Common/Common.xcodeproj/project.pbxproj
  Common/CommonImplementations/Logger/CrashlyticsLogger.swift
  Common/CommonImplementations/Logger/CrashlyticsLoggerTests.swift
  Common/CommonImplementations/Logger/CrashlyticsProtocol.swift
  MultisigWallet/MultisigWalletApplication/EthereumApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/DomainRegistry.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BaseDeploymentDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/Wallet.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
  safe/safe/AppDelegate.swift
  safe/safe/MultisigWalletConfigurator.swift
Labels: bug

#872 GH-864 ui adjustments
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/IntroContentView.swift
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/connect-browser-extension/connect-intro-icon.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/connect-browser-extension/connect-intro-icon.imageset/connect-intro-icon.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/connect-browser-extension/connect-intro-icon.imageset/connectBrowserWithPhone.pdf
  SafeUIKit/SafeUIKit/AttributedStringStyle.swift
Labels: bug

#874 Feature/gh 873 logging
  Common/Common/JSONHTTPClient.swift
  IdentityAccess/IdentityAccessImplementations/biometry/BiometricService.swift
  MultisigWallet/MultisigWalletApplication/EthereumApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/TokenListItemApplicationTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/Wallet.swift
  MultisigWallet/MultisigWalletImplementations/Services/HTTPGnosisTransactionRelayService.swift
  MultisigWallet/MultisigWalletImplementations/Services/HTTPNotificatonService.swift
  MultisigWallet/MultisigWalletImplementations/Services/SynchronisationService.swift
  safe/safe/AppDelegate.swift
  safe/safe/PushTokensService.swift
Labels: maintenance

#875 Feature/gh 871 release
  CHANGELOG.rst
  RELEASE.md
  safe/remoteNotificationHandler/Info.plist
  safe/safe/Info.plist
  safe/safe/Tests-Info.plist
  safe/safeUITests/Info.plist
Labels: maintenance

#879 Feature/gh 876
  MultisigWallet/MultisigWalletDomainModel/Wallet/TransactionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/TransactionDomainServiceTests.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/DBTokeListItemRepository.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/DBWalletRepository.swift
  MultisigWallet/MultisigWalletImplementations/Services/SynchronisationService.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/MenuTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SelectSafe/SelectSafeCommand.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  safe/safe.xcodeproj/project.pbxproj
  safe/safe/Migrations/M0001_UpdateProcessedTransactionsMigration.swift
  safe/safe/Migrations/Migrations.swift
  safe/safe/PushTokensService.swift
Labels: bug

#880 GH-878 fixed
  MultisigWallet/MultisigWalletApplication/EthereumApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/Account/AccountUpdateDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Ethereum/ExternallyOwnedAccountRepository.swift
Labels: bug

#887 Feature/gh 882 fee
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/RBEReviewTransactionViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewModel.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendReviewViewController.swift
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
Labels: bug

#889 Feature/gh 886 send balance
  IdentityAccess/IdentityAccessImplementations/biometry/BiometricService.swift
  IdentityAccess/Localizable.strings
  MultisigWallet/MultisigWalletApplication/MockWalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/PasswordViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/PasswordViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewModel.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PaymentMethod/PaymentMethodViewControllerTests.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/Unlock/UnlockViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/Unlock/UnlockViewControllerTests.swift
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
Labels: bug

#891 GH-884 fix Etherscan button in safe recovery fee paid vc.
  MultisigWallet/MultisigWalletApplication/RecoveryApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/FeePaidViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverFeePaidViewController.swift
Labels: bug

#890 Feature/gh 883 scan qr code wrong error
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreateSafeFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/TwoFA/TwoFAViewController.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
Labels: bug

#894 GH-893 skip the not enough funds rule if fee balance not available
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewController.swift
Labels: bug

#919 GH-912 WCMenuCommand
  SafeUIKit/SafeAppUI/MainFlow/Menu/MenuTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/MenuTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCMenuCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCMenuCommandTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCSessionListViewController.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
Labels: feature

#922 Feature/gh 902 wc session list ui
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/AssetView/AssetViewViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/BasicTableViewCell+WCSessionData.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCMenuCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCSessionListTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCSessionListTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCSessionListViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Tokens/BasicTableViewCell+TokenData.swift
  SafeUIKit/SafeAppUI/MainFlow/Tokens/ManageTokens/AddTokenTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Tokens/ManageTokens/ManageTokensTableViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PaymentMethod/BasePaymentMethodViewController.swift
  SafeUIKit/SafeAppUI/UIAlertController+Safe.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Components/BasicTableViewCell/BasicTableViewCell.swift
Labels: feature
