Repository gnosis/safe-ios, pull requests merged in 2019-04, with the labels that each got.

#653 Feature/gh 652
  Gemfile.lock
  encrypted_files.tar.enc
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
Labels: maintenance

#654 GH-558 added order by clauses to sql
  Common/CommonImplementations/TableSchema.swift
  IdentityAccess/IdentityAccessImplementations/persistence/SingleUserRepository/DBSingleUserRepository.swift
  MultisigWallet/MultisigWalletImplementations/DBAccountRepository.swift
  MultisigWallet/MultisigWalletImplementations/DBTokeListItemRepository.swift
  MultisigWallet/MultisigWalletImplementations/DBTransactionRepository.swift
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
Labels: bug

#658 Feature/gh 643
  Common/Common.xcodeproj/project.pbxproj
  Common/Common/Tracker/Tracker.swift
  Common/Common/Tracker/TrackerTests.swift
  Common/CommonImplementations/Tracker/ConsoleTracker.swift
  Common/CommonImplementations/Tracker/FirebaseTrackingHandler.swift
  MultisigWallet/MultisigWalletApplication/EventRelayTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/MainTrackingEvents.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/MenuTableViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/MenuTrackingEvent.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/SafeAddress/SafeAddressViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/SendTrackingEvent.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/ManageTokens/AddTokenTableViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/ManageTokens/ManageTokensTableViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/TokensTableViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/TransactionDetails/TransactionDetailsViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/TransactionList/TransactionsTableViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/MasterPasswordFlow/PasswordViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/OnboardingTrackingEvent.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/OnboardingTrackingEvents.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/GuidelinesViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafeViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/PaperWalletSetupFlow/ConfirmMnemonicViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/PaperWalletSetupFlow/SaveMnemonicViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/SafeCreationViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/SetupSafeOptionsViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/StartViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/TermsAndConditionsViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PairWithBrowserExtension/PairWithBrowserExtensionViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/Unlock/UnlockViewController.swift
  SafeUIKit/SafeAppUI/UIViewController+Tracking.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  safe/safe/AppDelegate.swift
  safe/safeUITests/NewSafe/ConfirmMnemonicUITests.swift
Labels: feature

#661 GH-645 added info plist
  safe/safe/Info.plist
Labels: maintenance

#663 GH-400 added new state waiting for first deposit
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/WalletApplicationServiceTests.swift
  MultisigWallet/MultisigWalletApplication/WalletStateEnum.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/Wallet.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/WalletStates.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/SafeCreationViewController.swift
Labels: improvement

#657 Feature/gh 637 change password
  IdentityAccess/IdentityAccessApplication/AuthenticationApplicationService.swift
  IdentityAccess/IdentityAccessApplication/MockAuthenticationService.swift
  IdentityAccess/IdentityAccessDomainModel/IdentityService/IdentityService.swift
  IdentityAccess/IdentityAccessDomainModel/IdentityService/IdentityServiceTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/CommonTransactionViews/TransactionParticipantView.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/CommonTransactionViews/TransactionValueView.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ChangePassword/ChangePassword.storyboard
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ChangePassword/ChangePasswordCommand.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ChangePassword/ChangePasswordFlowCoordinator.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ChangePassword/ChangePasswordFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ChangePassword/NewPasswordVerifiableInput.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ChangePassword/NewPasswordVerifiableInputTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ChangePassword/SetupNewPasswordViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ChangePassword/SetupNewPasswordViewControllerTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ChangePassword/VerifyCurrentPasswordViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ChangePassword/VerifyCurrentPasswordViewControllerTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/MenuTableViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/MenuTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/NewTransaction/FundsTransferTransactionViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/SegmentBar/SegmentBar.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/TokensHeaderView.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/TransactionList/TransactionTableViewCell.swift
  SafeUIKit/SafeAppUI/Authenticator.swift
  SafeUIKit/SafeAppUI/Colors.txt
  SafeUIKit/SafeAppUI/MenuCommand.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/MasterPasswordFlow/PasswordViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafeViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/PaperWalletSetupFlow/ConfirmMnemonicViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/Unlock/UnlockViewController.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeAppUI/generated/Colors.swift
  SafeUIKit/SafeAppUI/generated/Sotryboards.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Colors.txt
  SafeUIKit/SafeUIKit/Components/AddressInput/AddressInput.swift
  SafeUIKit/SafeUIKit/Components/EthereumAddressLabel/FullEthereumAddressLabel.swift
  SafeUIKit/SafeUIKit/Components/LoadingTitleView/LoadingTitleView.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/TextInput/TextInput.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/TextInput/TextInputTests.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/VerifiableInput/RuleLabel.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/VerifiableInput/RuleLabel.xib
  SafeUIKit/SafeUIKit/Components/TextInputs/VerifiableInput/RuleLabelTests.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/VerifiableInput/VerifiableInput.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/VerifiableInput/VerifiableInput.xib
  SafeUIKit/SafeUIKit/Components/TextInputs/VerifiableInput/VerifiableInputTests.swift
  SafeUIKit/SafeUIKit/Components/TokenInputs/TokenInput/TokenInput.swift
  SafeUIKit/SafeUIKit/Components/TokenInputs/TokenInput/TokenInputTests.swift
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/address-input/dots.imageset/Contents.json
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/address-input/dots.imageset/Three_dots.pdf
  SafeUIKit/SafeUIKit/generated/Assets.swift
  SafeUIKit/SafeUIKit/generated/Colors.swift
  SafeUIKit/SafeUIKitDemo/DetailControllers/AddressInputViewController.swift
  SafeUIKit/SafeUIKitDemo/DetailControllers/TextInputViewController.swift
  SafeUIKit/SafeUIKitDemo/DetailControllers/TokenInputViewController.swift
  SafeUIKit/SafeUIKitDemo/DetailControllers/VerifiableInputViewController.swift
  SafeUIKit/SafeUIKitDemo/Main/Base.lproj/Main.storyboard
Labels: feature

#670 Feature/gh 665 setup password redesign
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ChangePassword/ChangePassword.storyboard
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ChangePassword/NewPasswordVerifiableInputTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ChangePassword/SetupNewPasswordViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ChangePassword/SetupNewPasswordViewControllerTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/NewTransaction/KeyboardAvoidingBehavior.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/MasterPasswordFlow/MasterPassword.storyboard
  SafeUIKit/SafeAppUI/OnboardingFlow/MasterPasswordFlow/MasterPasswordFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/MasterPasswordFlow/PasswordViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/MasterPasswordFlow/PasswordViewControllerTests.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/MasterPasswordFlow/VerifiableInput+Rules.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/PaperWalletSetupFlow/ConfirmMnemonicViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/PaperWalletSetupFlow/ConfirmMnemonicViewControllerTests.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/SetupSafeOptionsViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/StartViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/Unlock/UnlockViewController.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Colors.txt
  SafeUIKit/SafeUIKit/Components/BackgroundImageView/BackgroundImageView.swift
  SafeUIKit/SafeUIKit/Components/CardView/CardView.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/VerifiableInput/RuleLabel.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/VerifiableInput/RuleLabelTests.swift
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/background-image.imageset/Contents.json
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/background-image.imageset/splashBackgroundScrim50.jpg
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/background-image.imageset/splashBackgroundScrim50@2x.jpg
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/background-image.imageset/splashBackgroundScrim50@3x.jpg
  SafeUIKit/SafeUIKit/generated/Assets.swift
  SafeUIKit/SafeUIKit/generated/Colors.swift
  SafeUIKit/SafeUIKitDemo/DetailControllers/CardViewViewController.swift
  SafeUIKit/SafeUIKitDemo/Main/Main.storyboard
Labels: improvement

#672 Feature/gh 646
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/EthereumApplicationServiceTests.swift
  MultisigWallet/MultisigWalletApplication/EventRelayTests.swift
  MultisigWallet/MultisigWalletApplication/SystemInfo.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceConfiguration.swift
  MultisigWallet/MultisigWalletDomainModel/NotificationService/MockNotificationService.swift
  MultisigWallet/MultisigWalletDomainModel/NotificationService/NotificationDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/NotificationService/NotificationRequests/AuthRequest.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/MockNotificationService1.swift
  MultisigWallet/MultisigWalletImplementations/HTTPNotificatonService.swift
  encrypted_files.tar.enc
  safe/safe/AppConfig.swift
  safe/safe/AppDelegate.swift
Labels: feature

#677 Feature/gh 675
  Gemfile.lock
  SafeUIKit/SafeAppUI/OnboardingFlow/MasterPasswordFlow/MasterPasswordFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/MasterPasswordFlow/PasswordViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/MasterPasswordFlow/VerifiableInput+Rules.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/AbortSafeCreationAlertController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/GuidelinesViewController+NewSafe.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafeViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/PaperWalletSetupFlow/SaveMnemonicViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/SafeCreationViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/RecoverSafe/AddressInputViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/RecoverSafe/GuidelinesViewController+RecoverSafe.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/SetupSafeOptionsViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/StartViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/TermsAndConditionsViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PairWithBrowserExtension/PairWithBrowserExtensionViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/Unlock/Unlock.storyboard
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/Unlock/UnlockViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/Unlock/UnlockViewControllerTests.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit/QRCodeScanner/ScanQRCodeHandler.swift
  SafeUIKit/SafeUIKit/QRCodeScanner/ScannerViewController.swift
  SafeUIKit/SafeUIKit/en.lproj/Localizable.strings
  safe/safeUITests/SafeAppUI.strings
  safe/safeUITests/UITestCase.swift
  safe/safeUITests/safeUIKit.strings
  safe/safeUITests/screens/OnboardingFlow/PendingSafeScreen.swift
Labels: feature

#683 Feature/gh 682
  SafeUIKit/SafeAppUI/OnboardingFlow/MasterPasswordFlow/MasterPassword.storyboard
  SafeUIKit/SafeAppUI/OnboardingFlow/MasterPasswordFlow/PasswordViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/MasterPasswordFlow/PasswordViewController.xib
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafe.storyboard
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafeViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/PaperWalletSetupFlow/ConfirmMnemonicViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/PaperWalletSetupFlow/SaveMnemonicViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/SafeCreationFailedAlertController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/SafeCreationViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/RecoverSafe/AddressInputViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoveryInProgressViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/SetupSafe.storyboard
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/SetupSafeOptionsViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/TermsAndConditionsViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/BaseInputViewController.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeAppUI/generated/Sotryboards.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  safe/safeUITests/NewSafe/PendingSafeScreenUITests.swift
  safe/safeUITests/NewSafe/SaveMnemonicUITests.swift
  safe/safeUITests/SafeAppUI.strings
  safe/safeUITests/screens/OnboardingFlow/NewSafeGuidelinesScreen.swift
  safe/safeUITests/screens/OnboardingFlow/NewSafeScreen.swift
  safe/safeUITests/screens/OnboardingFlow/PaperWalletSetupFlow/ConfirmMnemonicScreen.swift
  safe/safeUITests/screens/OnboardingFlow/PaperWalletSetupFlow/SaveMnemonicScreen.swift
Labels: feature

#685 Feature/gh 676 main screen localisation
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Main.storyboard
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Main/MainContentViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Main/MainViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/SafeAddress/SafeAddressViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/AddTokenFooterView.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/AddTokenFooterView.xib
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/ManageTokens/ManageTokensTableViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/TransactionDetails/StatusTransactionParameterView.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/TransactionDetails/TransactionDetailsViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/TransactionDetails/TransactionDetailsViewControllerTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/TransactionList/TransactionTableViewCell.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/TransactionList/TransactionsEmptyView.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/TransactionList/TransactionsGroupHeaderView.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/SafeCreationViewController.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
Labels: improvement

#687 Feature/gh 668 menu localisation
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ChangePassword/ChangePasswordCommand.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ChangePassword/SetupNewPasswordViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ChangePassword/VerifyCurrentPasswordViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ConnectBrowserExtension/ConnectBrowserExtensionLaterCommand.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/DisconnectBrowserExtension/DisconnectBrowserExtensionCommand.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/MenuTableViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/ReplaceBrowserExtensionCommand.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ResyncBrowserExtension/ResyncWithBrowserExtensionCommand.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/ManageTokens/AddTokenTableViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/ManageTokens/ManageTokensTableViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/SafeCreationViewController.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
Labels: improvement

#690 Feature/gh 689
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceRecoveryPhrase/ReplaceRecoveryPhraseReviewTransactionViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceRecoveryPhrase/ReplaceRecoveryPhraseViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/SupportFlowCoordinator.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/OnboardingFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafe.storyboard
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverSafe.storyboard
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoveryInProgressViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/RecoverSafe/ReviewRecoveryTransactionViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/RecoveryPhraseInputViewController.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit/Components/TransactionHeaderView/TransactionHeaderView.xib
  safe/safeUITests/SafeAppUI.strings
Labels: feature

#691 Feature/gh 689 dups
  scripts/find_duplicate_localizations.rb
Labels: improvement

#693 GH-689 new and updated keys
  IdentityAccess/IdentityAccessImplementations/biometry/BiometricService.swift
  IdentityAccess/IdentityAccessImplementations/en.lproj/Localizable.strings
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/FeeCalculationError.swift
  MultisigWallet/MultisigWalletApplication/Localizable.strings
  MultisigWallet/MultisigWalletApplication/SystemInfo.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceError.swift
  MultisigWallet/MultisigWalletApplication/en.lproj/Localizable.strings
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/AppVersionTableViewCell.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/Intro/RBEIntroViewControllerErrorState.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ResyncBrowserExtension/ResyncWithBrowserExtensionCommand.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/TokensHeaderView.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/TransactionList/TransactionsGroupHeaderView.swift
  SafeUIKit/SafeAppUI/ErrorHandler.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafeViewController.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  safe/IdentityAccessImplementationsResources.bundle/_CodeSignature/CodeDirectory
  safe/IdentityAccessImplementationsResources.bundle/_CodeSignature/CodeRequirements-1
  safe/IdentityAccessImplementationsResources.bundle/_CodeSignature/CodeResources
  safe/IdentityAccessImplementationsResources.bundle/en.lproj/Localizable.strings
  safe/safeUITests/SafeAppUI.strings
  safe/safeUITests/UITestCase.swift
Labels: feature

#694 GH-689 Added linting to translations
  scripts/find_duplicate_localizations.rb
  scripts/lint_localizations.rb
  scripts/pull_translations.sh
Labels: improvement

#695 GH-689 Updated keys
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/PaperWalletSetupFlow/SaveMnemonicViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/TermsAndConditionsViewController.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit/Components/BigButton/CheckmarkButton.swift
  SafeUIKit/SafeUIKit/Components/LoadingTitleView/LoadingTitleView.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/VerifiableInput/RuleLabel.swift
  SafeUIKit/SafeUIKit/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKitDemoUITests/safeUIKitDemoUITests.swift
  safe/remoteNotificationHandler/en.lproj/Localizable.strings
  safe/safe/PushLocalizationStrings.swift
  safe/safe/en.lproj/Localizable.strings
  safe/safeUITests/safeUIKit.strings
  safe/safeUITests/screens/OnboardingFlow/MasterPasswordFlow/Rule.swift
  safe/safeUITests/screens/OnboardingFlow/NewSafeScreen.swift
Labels: improvement

#697 Feature/gh 696 warnings
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/RecoveryApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/WalletApplicationServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BaseDeploymentDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/Wallet.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/MenuTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/Intro/RBEIntroViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceRecoveryPhrase/ReplaceRecoveryPhraseViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/NewTransaction/FundsTransferTransactionViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/NewTransaction/KeyboardAvoidingBehaviorTests.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/SafeCreationViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/SafeCreationViewControllerTests.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/RecoverSafe/ReviewRecoveryTransactionViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransactionViewController.swift
  SafeUIKit/SafeAppUI/SafeAppUIAlerts.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Components/QRCodeInput/QRCodeInputTests.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/TextInput/TextInput.swift
  SafeUIKit/SafeUIKit/Components/TokenInput/TokenBounds.swift
  SafeUIKit/SafeUIKit/Components/TokenInput/TokenInput.swift
  SafeUIKit/SafeUIKit/Components/TokenInput/TokenInputTests.swift
  SafeUIKit/SafeUIKit/Components/TokenInputs/TokenDoubleInput/ApproximateCurrencyFormatter.swift
  SafeUIKit/SafeUIKit/Components/TokenInputs/TokenDoubleInput/ApproximateCurrencyFormatterTests.swift
  SafeUIKit/SafeUIKit/Components/TokenInputs/TokenDoubleInput/TokenDoubleInput.swift
  SafeUIKit/SafeUIKit/Components/TokenInputs/TokenDoubleInput/TokenDoubleInput.xib
  SafeUIKit/SafeUIKit/Components/TokenInputs/TokenDoubleInput/TokenDoubleInputTests.swift
  SafeUIKit/SafeUIKit/Components/TransactionHeaderView/TransactionHeaderViewTests.swift
  SafeUIKit/SafeUIKit/UITextField+TokenInput.swift
  SafeUIKit/SafeUIKitDemo/DetailControllers/TokenDoubleInputViewController.swift
  SafeUIKit/SafeUIKitDemo/Main/Main.storyboard
  safe/safe.xcodeproj/project.pbxproj
  safe/safe/AppDelegate.swift
  safe/safe/IdentityAccessConfigurator.swift
  safe/safe/IntegrationTests/GnosisTransactionRelayServiceTests.swift
  safe/safe/IntegrationTests/Safe.swift
  safe/safe/MultisigWalletConfigurator.swift
  safe/safeUITests/NewSafe/NewSafeScreenUITests.swift
Labels: improvement

#699 GH-646 updated with proper data structure
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/NotificationService/NotificationRequests/AuthRequest.swift
Labels: feature

#700 Feature/gh 698 licenses
  MultisigWallet/MultisigWalletApplication/SystemInfo.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceConfiguration.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/AppVersionTableViewCell.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/MenuTableViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/MenuTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/Support/LicensesCommand.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/Support/PrivacyPolicyCommand.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/Support/TermsCommand.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/MenuTrackingEvent.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/SupportFlowCoordinator.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  encrypted_files.tar.enc
  safe/safe/AppConfig.swift
Labels: improvement

#704 GH-668 fixes crash
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/NewTransaction/FundsTransferTransactionViewController.swift
Labels: bug

#703 GH-649 added logging
  Library/Library.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/EthereumApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletImplementations/EncryptionService.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/MenuTableViewController.swift
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
  safe/IdentityAccessImplementationsResources.bundle/_CodeSignature/CodeDirectory
  safe/IdentityAccessImplementationsResources.bundle/_CodeSignature/CodeRequirements-1
Labels: bug

#705 GH-681 GH-680 suppress error logs for the reported errors
  MultisigWallet/MultisigWalletImplementations/SynchronisationService.swift
Labels: bug

#707 Feature/gh 659 adjust address component
  SafeUIKit/SafeUIKit/Components/AddressInput/AddressInput.swift
  SafeUIKit/SafeUIKit/Components/AddressInput/AddressInputTests.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/TextInput/TextInput.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/TextInput/TextInputTests.swift
  SafeUIKit/SafeUIKit/Components/TokenInput/TokenInput.swift
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/address-input/address-icon-tmp.imageset/Contents.json
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/address-input/address-icon-tmp.imageset/contact.pdf
  SafeUIKit/SafeUIKit/generated/Assets.swift
Labels: improvement

#708 Feature/gh 646 auth response
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceConfiguration.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/BaseWalletApplicationServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/NotificationService/MockNotificationService.swift
  MultisigWallet/MultisigWalletDomainModel/NotificationService/NotificationDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/NotificationService/NotificationRequests/AuthRequest.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/MockNotificationService1.swift
  MultisigWallet/MultisigWalletImplementations/HTTPNotificatonService.swift
  encrypted_files.tar.enc
  safe/safe/AppConfig.swift
  safe/safe/IntegrationTests/HTTPNotificatonServiceTests.swift
Labels: feature

#709 GH-639 Updated INFURA keys
  encrypted_files.tar.enc
Labels: improvement

#710 Feature/gh 659 adjust address component
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/PaperWalletSetupFlow/SaveMnemonicViewController.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Colors.txt
  SafeUIKit/SafeUIKit/Components/CardView/CardView.swift
  SafeUIKit/SafeUIKit/Components/FeedbackTooltip/FeedbackTooltip.swift
  SafeUIKit/SafeUIKit/generated/Colors.swift
  SafeUIKit/SafeUIKitDemo/DetailControllers/CardViewViewController.swift
  SafeUIKit/SafeUIKitDemo/DetailControllers/FeedbackTooltipViewController.swift
  SafeUIKit/SafeUIKitDemo/Main/Main.storyboard
Labels: feature

#711 GH-674 implemented time updates
  Common/CommonImplementations/DBMigrationService.swift
  Common/CommonImplementations/DBMigrationServiceTests.swift
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletDomainModel/Ethereum/EthereumNodeDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Transaction/Transaction.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/AllDeploymentStatesTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/MockEthereumNodeService1.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/TransactionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/TransactionDomainServiceTests.swift
  MultisigWallet/MultisigWalletImplementations/DemoEthereumNodeService.swift
  MultisigWallet/MultisigWalletImplementations/MockEthereumNodeService.swift
  MultisigWallet/MultisigWalletImplementations/MockSynchronisationService.swift
  MultisigWallet/MultisigWalletImplementations/SynchronisationService.swift
  MultisigWallet/MultisigWalletImplementations/infura/InfuraEthereumNodeService.swift
  MultisigWallet/MultisigWalletImplementations/infura/requests/GetBlockByHashRequest.swift
  MultisigWallet/MultisigWalletImplementations/infura/requests/GetTransactionReceiptRequest.swift
  safe/safe.xcodeproj/project.pbxproj
  safe/safe/IdentityAccessConfigurator.swift
  safe/safe/IntegrationTests/InfuraEthereumNodeServiceTests.swift
  safe/safe/Migrations/0001_UpdateProcessedTransactionsMigration.swift
  safe/safe/MultisigWalletConfigurator.swift
Labels: bug

#713 GH-712 bump version
  CHANGELOG.rst
  safe/remoteNotificationHandler/Info.plist
  safe/safe/Info.plist
  safe/safe/Tests-Info.plist
  safe/safeUITests/Info.plist
Labels: maintenance

#715 Feature/gh 714
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Main.storyboard
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ChangePassword/ChangePassword.storyboard
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ResyncBrowserExtension/ResyncWithBrowserExtensionCommand.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/MasterPasswordFlow/VerifiableInput+Rules.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafe.storyboard
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverSafe.storyboard
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/Unlock/Unlock.storyboard
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit/Components/AddressInput/AddressInput.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/TextInput/TextInput.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/VerifiableInput/VerifiableInput.swift
  SafeUIKit/SafeUIKit/Components/TokenInput/TokenInput.swift
  SafeUIKit/SafeUIKitDemo/Main/Main.storyboard
Labels: improvement

#716 GH-714 added placeholder and resizing height
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransactionViewController.swift
  SafeUIKit/SafeUIKit/Components/TransactionHeaderView/TransactionHeaderView.swift
  SafeUIKit/SafeUIKit/Components/TransferView/SettingsTransactionHeaderView.xib
Labels: bug

#720 Feature/gh 718
  MultisigWallet/MultisigWalletDomainModel/Ethereum/Token/TokenList.swift
  MultisigWallet/MultisigWalletDomainModel/Transaction/Transaction.swift
  MultisigWallet/MultisigWalletDomainModel/Transaction/TransactionStatus.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/Owner.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/WalletStates.swift
Labels: bug

#721 Release/1.2.0
  CHANGELOG.rst
  Gemfile.lock
  MultisigWallet/MultisigWalletDomainModel/Ethereum/Token/TokenList.swift
  MultisigWallet/MultisigWalletDomainModel/Transaction/Transaction.swift
  MultisigWallet/MultisigWalletDomainModel/Transaction/TransactionStatus.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/Owner.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/WalletStates.swift
  RELEASE.md
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Main.storyboard
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ChangePassword/ChangePassword.storyboard
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ResyncBrowserExtension/ResyncWithBrowserExtensionCommand.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/MasterPasswordFlow/VerifiableInput+Rules.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafe.storyboard
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverSafe.storyboard
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransactionViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/Unlock/Unlock.storyboard
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit/Components/AddressInput/AddressInput.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/TextInput/TextInput.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/VerifiableInput/VerifiableInput.swift
  SafeUIKit/SafeUIKit/Components/TokenInput/TokenInput.swift
  SafeUIKit/SafeUIKit/Components/TransactionHeaderView/TransactionHeaderView.swift
  SafeUIKit/SafeUIKit/Components/TransferView/SettingsTransactionHeaderView.xib
  SafeUIKit/SafeUIKitDemo/Main/Main.storyboard
  safe/remoteNotificationHandler/Info.plist
  safe/safe/Info.plist
  safe/safe/Tests-Info.plist
  safe/safeUITests/Info.plist
Labels: maintenance

#724 Feature/gh 723 send rename
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Main.storyboard
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/MainFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Send/SendInputViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Send/SendInputViewControllerTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Send/SendInputViewModel.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Send/SendInputViewModelTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Send/SendReviewViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Send/SendReviewViewControllerTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Send/SendTrackingEvent.swift
  SafeUIKit/SafeAppUI/KeyboardAvoidingBehavior.swift
  SafeUIKit/SafeAppUI/KeyboardAvoidingBehaviorTests.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransactionViewControllerTests.swift
  SafeUIKit/SafeAppUI/generated/Sotryboards.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKitDemo/Main/SendInputDemoViewController.swift
Labels: improvement
