Repository gnosis/safe-ios, pull requests merged in 2019-05, with the labels that each got.

#727 Feature/gh 723 send ui
  Common/Common/TokenData.swift
  Gemfile.lock
  MultisigWallet/MultisigWalletApplication/FeeCalculationError.swift
  MultisigWallet/MultisigWalletApplication/en.lproj/Localizable.strings
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Main.storyboard
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/Intro/Common/FeeCalculation/FeeCalculation.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/Intro/Common/FeeCalculation/FeeCalculationAssetLine+TextStyle.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/Intro/Common/FeeCalculation/FeeCalculationAssetLine.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/Intro/Common/FeeCalculation/FeeCalculationErrorLine.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/Intro/Common/FeeCalculation/FeeCalculationLine.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/Intro/Common/FeeCalculation/FeeCalculationView.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/Intro/EthFeeCalculation.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Send/FeeCalculationAssetLine+TokenData.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Send/SendERC20FeeCalculation.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Send/SendEthFeeCalculation.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Send/SendInputViewController.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/AccountBalanceView.swift
  SafeUIKit/SafeUIKit/AttributedStringStyle.swift
  SafeUIKit/SafeUIKit/Components/AmountLabel/AmountLabel.swift
  SafeUIKit/SafeUIKit/Components/EthereumAddressLabel/EthereumAddressLabel.swift
  SafeUIKit/SafeUIKit/Components/FeedbackTooltip/FeedbackTooltip.swift
  SafeUIKit/SafeUIKit/Components/FeedbackTooltip/TooltipSource.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/VerifiableInput/RuleLabel.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/VerifiableInput/VerifiableInput.swift
  SafeUIKit/SafeUIKit/Components/TokenInput/TokenInput.swift
  SafeUIKit/SafeUIKit/String+Extensions.swift
  SafeUIKit/SafeUIKit/TokenNumberFormatter.swift
Labels: feature

#728 GH-726 fix migrations bug; add skipMigraionsBeforeAndIncluding method;
  Common/CommonImplementations/DBMigrationService.swift
  Common/CommonImplementations/DBMigrationServiceTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/TransactionList/TransactionsTableViewControllerRegressionTests.swift
  safe/safe.xcodeproj/project.pbxproj
  safe/safe/Migrations/M0001_UpdateProcessedTransactionsMigration.swift
  safe/safe/Migrations/Migrations.swift
  safe/safe/MultisigWalletConfigurator.swift
Labels: bug, improvement

#730 Feature/gh 723 send input2
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Main.storyboard
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ChangePassword/SetupNewPasswordViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/Intro/Common/FeeCalculation/FeeCalculationAssetLine+TextStyle.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/Intro/Common/FeeCalculation/FeeCalculationAssetLine.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Send/SendInputViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/DashedSeparatorView.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/TokensHeaderView.swift
  SafeUIKit/SafeAppUI/KeyboardAvoidingBehavior.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/MasterPasswordFlow/PasswordViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/PaperWalletSetupFlow/ConfirmMnemonicViewController.swift
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/transaction-edit/settings.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/transaction-edit/settings.imageset/settings.pdf
  SafeUIKit/SafeAppUI/generated/Assets.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Components/FeedbackTooltip/FeedbackTooltip.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/TextInput/TextInput.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/VerifiableInput/VerifiableInput.swift
Labels: feature

#739 Feature/gh 737 payment method in menu
  MultisigWallet/MultisigWalletApplication/MockWalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/WalletApplicationServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/Wallet.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/WalletTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/FeePaymentMethod/FeePaymentMethodCommand.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/MenuItemTableViewCell.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/MenuTableViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/MenuTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PaymentMethodViewController.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
Labels: feature

#740 Feature/gh 738 send success
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Main.storyboard
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Send/SuccessViewController+SendSuccess.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/SuccessViewController.swift
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/congratulations.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/congratulations.imageset/congratulations.pdf
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeAppUI/generated/Assets.swift
  SafeUIKit/SafeAppUI/generated/Sotryboards.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
Labels: feature

#748 Feature/gh 747 token balance cell
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Main/MainViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/MenuItemTableViewCell.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/MenuTableViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/MenuTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceRecoveryPhrase/ReplaceRecoveryPhraseViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/SafeAddress/SafeAddressViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/BasicTableViewCell+TokenData.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/ManageTokens/AddTokenTableViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/ManageTokens/AddTokenTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/ManageTokens/ManageTokensTableViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/TokensTableViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/TokensTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/TransactionDetails/TransactionDetailsViewController.swift
  SafeUIKit/SafeAppUI/Colors.txt
  SafeUIKit/SafeAppUI/MenuCommand.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoveryInProgressViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PaymentMethodViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/Unlock/UnlockViewController.swift
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/token-icons/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/token-icons/ETH.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/token-icons/ETH.imageset/logoTokenEth.png
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/token-icons/ETH.imageset/logoTokenEth@2x.png
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/token-icons/ETH.imageset/logoTokenEth@3x.png
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/token-icons/default-token.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/token-icons/default-token.imageset/placeholder.pdf
  SafeUIKit/SafeAppUI/generated/Assets.swift
  SafeUIKit/SafeAppUI/generated/Colors.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Colors.txt
  SafeUIKit/SafeUIKit/Components/BasicTableViewCell/BasicTableViewCell.swift
  SafeUIKit/SafeUIKit/Components/BasicTableViewCell/BasicTableViewCell.xib
  SafeUIKit/SafeUIKit/Components/BorderedButton/StandardButton.swift
  SafeUIKit/SafeUIKit/Components/ProgressView/ProgressView.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/TextInput/TextInput.swift
  SafeUIKit/SafeUIKit/Components/TokenBalanceCell/TokenBalanceTableViewCell.swift
  SafeUIKit/SafeUIKit/Components/TokenBalanceCell/TokenBalanceTableViewCell.xib
  SafeUIKit/SafeUIKit/generated/Colors.swift
Labels: improvement

#749 Feature/gh 746 create2 part1
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletDomainModel/EthereumContractProxy.swift
  MultisigWallet/MultisigWalletDomainModel/GnosisSafeContractProxy.swift
  MultisigWallet/MultisigWalletDomainModel/GnosisSafeContractProxyTests.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/SafeCreation2Request.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/TransactionRelayDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/MockTransactionRelayService1.swift
  MultisigWallet/MultisigWalletImplementations/Services/GnosisTransactionRelayService.swift
  MultisigWallet/MultisigWalletImplementations/Services/MockTransactionRelayService.swift
  safe/safe/IntegrationTests/GnosisTransactionRelayServiceTests.swift
Labels: feature

#750 Feature/gh 735 payment tokens services
  Common/CommonImplementations/DBEntityRepository.swift
  MultisigWallet/MultisigWalletApplication/TestFixture.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/TokenListItemApplicationTests.swift
  MultisigWallet/MultisigWalletDomainModel/Account/AccountUpdateDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Account/AccountUpdateDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Ethereum/Token/TokenListItemRepository.swift
  MultisigWallet/MultisigWalletImplementations/DatabaseRepositories/DBTokeListItemRepository.swift
  MultisigWallet/MultisigWalletImplementations/MockRepositories/InMemoryTokenListItemRepository.swift
  MultisigWallet/MultisigWalletImplementations/MockRepositories/TokenListItemRepositoryTests.swift
  MultisigWallet/MultisigWalletImplementations/Services/MockTokenListService.swift
Labels: feature

#758 Feature/gh 735 payment tokens vc
  MultisigWallet/MultisigWalletApplication/MockWalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/WalletApplicationServiceTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/MenuTrackingEvent.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/TokensTableViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/TokensTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PaymentMethod/PaymentMethodHeaderView.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PaymentMethod/PaymentMethodHeaderView.xib
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PaymentMethod/PaymentMethodViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PaymentMethod/PaymentMethodViewControllerTests.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PaymentMethodViewController.swift
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/checkmark.imageset/Check.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/checkmark.imageset/Contents.json
  SafeUIKit/SafeAppUI/TestExtensions.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeAppUI/generated/Assets.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Components/BackgroundHeaderFooterView/BackgroundHeaderFooterView.swift
  SafeUIKit/SafeUIKit/Components/BackgroundHeaderFooterView/TableHeaderStyle.swift
  SafeUIKit/SafeUIKit/Components/BasicTableViewCell/BasicTableViewCell.swift
  SafeUIKit/SafeUIKit/Components/BasicTableViewCell/BasicTableViewCell.xib
  SafeUIKit/SafeUIKit/Components/InfoLabel/InfoLabel.swift
  SafeUIKit/SafeUIKit/en.lproj/Localizable.strings
Labels: feature

#763 Feature/gh 761 fc merge
  SafeUIKit/SafeAppUI/AppFlow/AppFlowCoordinator.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/MainFlowCoordinatorAppTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/MainFlowCoordinatorOnboardingTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/MainFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/MasterPasswordFlow/MasterPassword.storyboard
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/MasterPasswordFlow/MasterPasswordFlowCoordinator.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/MasterPasswordFlow/MasterPasswordFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/MasterPasswordFlow/PasswordValidator.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/MasterPasswordFlow/PasswordValidatorTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/MasterPasswordFlow/PasswordViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/MasterPasswordFlow/PasswordViewController.xib
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/MasterPasswordFlow/PasswordViewControllerTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/MasterPasswordFlow/VerifiableInput+Rules.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/OnboardingTrackingEvent.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/GuidelinesViewController+NewSafe.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/GuidelinesViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/GuidelinesViewControllerTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafe.storyboard
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafeFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafeViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafeViewControllerTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/PaperWalletSetupFlow/ConfirmMnemonicViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/PaperWalletSetupFlow/ConfirmMnemonicViewControllerTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/PaperWalletSetupFlow/PaperWalletFlowCoordinator.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/PaperWalletSetupFlow/PaperWalletFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/PaperWalletSetupFlow/SaveMnemonicViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/PaperWalletSetupFlow/SaveMnemonicViewControllerTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/SafeCreationFailedAlertController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/SafeCreationViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/SafeCreationViewControllerTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/AddressInputViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/AddressInputViewControllerTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/GuidelinesViewController+RecoverSafe.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverSafe.storyboard
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverSafeFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverSafeTrackingEvent.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoveryInProgressViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoveryInProgressViewControllerTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/ReviewRecoveryTransactionViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/ReviewRecoveryTransactionViewControllerTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/SetupSafe.storyboard
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/SetupSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/SetupSafeFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/SetupSafeOptionsViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/SetupSafeOptionsViewControllerTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/StartViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/StartViewControllerTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/TermsAndConditionsViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/TermsAndConditionsViewControllerTests.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/OnboardingFlowCoordinator.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  encrypted_files.tar.enc
  safe/safe/AppDelegate.swift
  safe/safe/AppDelegateTests.swift
Labels: improvement

#766 GH-765 updated localization keys
  Gemfile.lock
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ConnectBrowserExtension/ConnectBrowserExtensionFlowCoordinator.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ConnectBrowserExtension/ConnectBrowserExtensionLaterCommand.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/DisconnectBrowserExtension/DisconnectBrowserExtensionCommand.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/DisconnectBrowserExtension/DisconnectBrowserExtensionFlowCoordinator.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/Intro/IntroContentView.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/RBEReviewTransactionViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/ReplaceBrowserExtensionCommand.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceRecoveryPhrase/ReplaceRecoveryPhraseCommand.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceRecoveryPhrase/ReplaceRecoveryPhraseReviewTransactionViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/TransactionDetails/TransactionDetailsViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/TransactionList/TransactionTableViewCell.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
Labels: maintenance, unplanned

#768 Feature/gh 760 funds transfer payment method - Batch 1
  MultisigWallet/MultisigWalletApplication/RecoveryApplicationService.swift
  MultisigWallet/MultisigWalletApplication/TokenData+Extensions.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/SendTransactionTests.swift
  MultisigWallet/MultisigWalletDomainModel/Transaction/Transaction.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/EstimateTransactionRequest.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/SubmitTransactionRequest.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ReplaceBrowserExtensionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/WalletSettingsDomainService.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/EthFeeCalculation.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/OwnerModificationFeeCalculation.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/RBEIntroViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/RBEIntroViewControllerInvalidState.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/RBEIntroViewControllerLoadingState.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/Tests/RBEIntroViewControllerInvalidStateTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/Tests/RBEIntroViewControllerLoadingStateTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/Tests/RBEIntroViewControllerReadyStateTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/RBEReviewTransactionViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceRecoveryPhrase/ReplaceRecoveryPhraseReviewTransactionViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/DifferentTransferAndPaymentTokensFeeCalculation.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/FeeCalculationAssetLine+TokenData.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SameTransferAndPaymentTokensFeeCalculation.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewModel.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendReviewViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendReviewViewControllerTests.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransactionViewController.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  safe/safe/IntegrationTests/GnosisTransactionRelayServiceTests.swift
  safe/safe/IntegrationTests/Safe.swift
Labels: feature

#770 Feature/gh 767 create or restore
  IdentityAccess/IdentityAccess.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/WalletSettingsApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/WalletSettingsDomainService.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinatorAppTests.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinatorCreateOrRestoreTests.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinatorOnboardingTests.swift
  SafeUIKit/SafeAppUI/MainFlow/MainViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/MenuTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/RBEIntroViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceRecoveryPhrase/ReplaceRecoveryPhraseCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/OnboardingCreateOrRestoreViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/OnboardingCreateOrRestoreViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/SetupSafe.storyboard
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/SetupSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/SetupSafeFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/UIBarButtonItem+Back.swift
  SafeUIKit/SafeAppUI/MainFlow/UIBarButtonItem+Items.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PairWithBrowserExtension/PairWithBrowserExtensionViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/RecoveryPhraseInputViewController.swift
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/onboarding/no-safes.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/onboarding/no-safes.imageset/No Safes.pdf
  SafeUIKit/SafeAppUI/generated/Assets.swift
  SafeUIKit/SafeAppUI/generated/Sotryboards.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
Labels: improvement

#773 Feature/gh 760 funds transfer payment method
  Common/Common/TokenData.swift
  MultisigWallet/MultisigWalletApplication/FeeCalculationError.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/en.lproj/Localizable.strings
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/EstimateTransactionRequest.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/FeeCalculationAssetLine+TokenData.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewModel.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewModelTests.swift
  SafeUIKit/SafeUIKit/Components/FeeCalculation/FeeCalculationAssetLine+TextStyle.swift
  SafeUIKit/SafeUIKit/Components/FeeCalculation/FeeCalculationAssetLine.swift
Labels: feature

#774 Feature/gh 771 formatters
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/RBEIntroViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/Tests/RBEIntroViewControllerInvalidStateTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/Tests/RBEIntroViewControllerReadyStateTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/SafeCreationViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/FeeCalculationAssetLine+TokenData.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendReviewViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Tokens/BasicTableViewCell+TokenData.swift
  SafeUIKit/SafeAppUI/MainFlow/Tokens/TokensTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/TransactionDetails/TransactionDetailsViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/TransactionList/TransactionsTableViewControllerTests.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Components/AmountLabel/AmountLabel.swift
  SafeUIKit/SafeUIKit/Components/AmountLabel/AmountLabelTests.swift
  SafeUIKit/SafeUIKit/Components/TokenInput/TokenInput.swift
  SafeUIKit/SafeUIKit/Components/TokenInput/TokenInputTests.swift
  SafeUIKit/SafeUIKit/Components/TransactionFeeView/TransactionFeeView.swift
  SafeUIKit/SafeUIKit/TokenFormatter.swift
  SafeUIKit/SafeUIKit/TokenFormatterTests.swift
  SafeUIKit/SafeUIKit/TokenNumberFormatter.swift
  SafeUIKit/SafeUIKit/en.lproj/Localizable.strings
Labels: feature

#778 GH-775 receive funds new design
  SafeUIKit/SafeAppUI/MainFlow/Main.storyboard
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/ReceiveFunds/ReceiveFunds.storyboard
  SafeUIKit/SafeAppUI/MainFlow/ReceiveFunds/ReceiveFundsViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/ReceiveFunds/ReceiveFundsViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/SafeAddress/SafeAddressViewController.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeAppUI/generated/Sotryboards.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Components/EthereumAddressLabel/FullEthereumAddressLabel.swift
  SafeUIKit/SafeUIKit/Components/FeedbackTooltip/TooltipSource.swift
  SafeUIKit/SafeUIKit/en.lproj/Localizable.strings
Labels: improvement

#784 Feature/gh 776 scroll header
  SafeUIKit/SafeAppUI/MainFlow/Main.storyboard
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/AssetView/AddTokenFooterView.xib
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/AssetView/AssetViewViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/AssetView/AssetViewViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/AssetView/TokensTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/HeaderScrollDelegate.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/MainContentViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/MainViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/MainViewControllerSegmentTests.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/MainViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/SegmentBar.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/SegmentBar/SegmentBarController.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/SegmentBarTests.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/TestSegmentBarNib.xib
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/TransactionView/TransactionViewViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/TransactionView/TransactionViewViewControllerRegressionTests.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/TransactionView/TransactionViewViewControllerTests.swift
  SafeUIKit/SafeAppUI/generated/Sotryboards.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKitDemo/DetailControllers/MySegmentViewController.swift
Labels: improvement

#787 Feature/gh 781 estimate safe creation
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/MockWalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/WalletApplicationServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/EstimateSafeCreationRequest.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/TransactionRelayDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/MockTransactionRelayService1.swift
  MultisigWallet/MultisigWalletImplementations/Services/HTTPGnosisTransactionRelayService.swift
  MultisigWallet/MultisigWalletImplementations/Services/MockTransactionRelayService.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/FeeIntroViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/FeeIntroViewControllerTests.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  safe/safe.xcodeproj/project.pbxproj
  safe/safe.xcodeproj/xcshareddata/xcschemes/safe.xcscheme
  safe/safe/IntegrationTests/HTTPGnosisTransactionRelayServiceTests.swift
  safe/safe/IntegrationTests/Safe.swift
  safe/safe/MultisigWalletConfigurator.swift
Labels: feature

#788 GH-777 added daily grouping
  MultisigWallet/MultisigWalletDomainModel/Wallet/TransactionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/TransactionDomainServiceTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Main.storyboard
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/MainViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/TransactionView/TransactionTableViewCell.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/TransactionView/TransactionViewViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/TransactionView/TransactionsGroupHeaderView.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
Labels: improvement

#789 GH-777 pending state
  SafeUIKit/SafeAppUI/MainFlow/Main.storyboard
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/HeaderScrollDelegate.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/TransactionView/TransactionTableViewCell.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/TransactionView/TransactionViewViewController.swift
Labels: improvement

#791 GH-790 added new CardViewController
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/TransactionView/TransactionViewViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/RBEIntroViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/OnboardingCreationFeeViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/ReceiveFunds/ReceiveFundsViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/UIBarButtonItem+Items.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/CardViewController/AddressDetailView.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/CardViewController/AddressDetailView.xib
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/CardViewController/CardViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/CardViewController/CardViewController.xib
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/CardViewController/FeeRequestView.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/CardViewController/FeeRequestView.xib
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PairWithBrowserExtension/PairWithBrowserExtension.storyboard
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PairWithBrowserExtension/PairWithBrowserExtensionViewController.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/BaseCustomView.swift
  SafeUIKit/SafeUIKit/UIView+Extensions.swift
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
  safe/IdentityAccessImplementationsResources.bundle/_CodeSignature/CodeDirectory
  safe/IdentityAccessImplementationsResources.bundle/_CodeSignature/CodeRequirements-1
Labels: improvement

#792 GH-790 added feePaid controller
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/FeePaidViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/FeePaidViewController.xib
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/OnboardingFeePaidViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverFeePaidViewController.swift
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/onboarding/creatingSafe.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/onboarding/creatingSafe.imageset/creatingSafe.pdf
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeAppUI/generated/Assets.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Colors.txt
  SafeUIKit/SafeUIKit/Components/FeeCalculation/FeeCalculationAssetLine.swift
  SafeUIKit/SafeUIKit/Components/SafeLabelTitleView/SafeLabelTitleView.swift
  SafeUIKit/SafeUIKit/generated/Colors.swift
Labels: improvement

#794 Feature/gh 783 creation fee intro
  MultisigWallet/MultisigWalletApplication/MockWalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/WalletApplicationServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Account/MockAccountUpdateService.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/EstimateSafeCreationRequest.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/TransactionRelayDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/MockTransactionRelayService1.swift
  MultisigWallet/MultisigWalletImplementations/Services/HTTPGnosisTransactionRelayService.swift
  MultisigWallet/MultisigWalletImplementations/Services/MockTransactionRelayService.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/OnboardingTrackingEvent.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/CreationFeeIntro/CreationFeeIntroHeaderView.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/CreationFeeIntro/CreationFeeIntroHeaderView.xib
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/CreationFeeIntro/OnboardingCreationFeeIntroViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/CreationFeeIntro/OnboardingCreationFeeIntroViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/CreationFeeIntro/OnboardingPaymentMethodViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/CreationFeeIntro/OnboardingPaymentMethodViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/FeeIntroViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/FeeIntroViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafeFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/OnboardingCreateOrRestoreViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverFeePaidViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PaymentMethod/BasePaymentMethodViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PaymentMethod/BasePaymentMethodViewControllerTests.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PaymentMethod/PaymentMethodFooterView.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PaymentMethod/PaymentMethodFooterView.xib
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PaymentMethod/PaymentMethodHeaderView.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PaymentMethod/PaymentMethodViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PaymentMethod/PaymentMethodViewControllerTests.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Components/InfoLabel/InfoLabel.swift
  SafeUIKit/SafeUIKit/Components/StandardButton/BigBorderedButton.swift
  SafeUIKit/SafeUIKit/Components/StandardButton/StandardButton.swift
Labels: feature

#796 Feature/gh 793 new safe flow
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/MockRecoveryApplicationService.swift
  MultisigWallet/MultisigWalletApplication/RecoveryApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/SendTransactionTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/WalletDomainService.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinatorAppTests.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinatorCreateOrRestoreTests.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinatorOnboardingTests.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/RBEIntroViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceRecoveryPhrase/ReplaceRecoveryPhraseViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/CreationProcessTracker.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafeFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/OnboardingCreationFeeViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/SafeCreationFailedAlertController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/SafeCreationViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/OnboardingFeePaidViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoveryInProgressViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/ReviewRecoveryTransactionViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/BaseInputViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/CardViewController/FeeRequestView.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/CardViewController/FeeRequestView.xib
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransactionViewController.swift
  SafeUIKit/SafeAppUI/SafeAppUIAlerts.swift
  SafeUIKit/SafeAppUI/SafeTestCase.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
Labels: improvement

#809 Feature/gh 808 intro
  SafeUIKit/SafeAppUI/MainFlow/CustomNavigationController.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinatorOnboardingTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ConnectBrowserExtension/ConnectBrowserExtensionFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ConnectBrowserExtension/ConnectBrowserExtensionFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/PairWithBrowserExtensionViewController+RBE.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/ReplaceBrowserExtensionFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/ReplaceBrowserExtensionFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/GuidelinesViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafe.storyboard
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafeFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverSafe.storyboard
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/MasterPassword.storyboard
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/MasterPasswordFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/MasterPasswordFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/OnboardingTermsViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/OnboardingTermsViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/OnboardingTrackingEvent.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/OnboardingWelcomeViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/OnboardingWelcomeViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/PasswordValidator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/PasswordValidatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/PasswordViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/PasswordViewController.xib
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/PasswordViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/VerifiableInput+Rules.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/BaseInputViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/CardViewController/CardViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PairWithBrowserExtension/PairWithBrowserExtension.storyboard
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/RecoveryPhraseInputViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/TwoFA/TwoFAView.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/TwoFA/TwoFAView.xib
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/TwoFA/TwoFAViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/TwoFA/TwoFAViewControllerTests.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/UIViewController+Back.swift
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/navbar-filled.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/navbar-filled.imageset/navbar-filled.pdf
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeAppUI/generated/Assets.swift
  SafeUIKit/SafeAppUI/generated/Sotryboards.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/AttributedStringStyle.swift
  SafeUIKit/SafeUIKit/Components/AddressInput/AddressInput.swift
  SafeUIKit/SafeUIKit/Components/BackgroundImageView/BackgroundImageView.swift
  SafeUIKit/SafeUIKit/Components/FeedbackTooltip/TooltipSource.swift
  SafeUIKit/SafeUIKit/Components/StandardButton/StandardButton.swift
  SafeUIKit/SafeUIKit/QRCodeScanner/ScannerViewController.swift
  SafeUIKit/SafeUIKit/QRCodeScanner/ScannerViewController.xib
  SafeUIKit/SafeUIKitDemo/Main/TermsAndConditionsDemoViewController.swift
Labels: improvement

#811 Feature/gh 807 manage tokens
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/TokenListItemApplicationTests.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/AssetView/AddTokenFooterView.xib
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/TransactionView/TransactionViewViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/TransactionView/TransactionsEmptyView.swift
  SafeUIKit/SafeAppUI/MainFlow/Tokens/BasicTableViewCell+TokenData.swift
  SafeUIKit/SafeAppUI/MainFlow/Tokens/ManageTokens/AddTokenTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Tokens/ManageTokens/AddTokenTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/EmptyResultsView.swift
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/no-results.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/no-results.imageset/emptyState.pdf
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeAppUI/generated/Assets.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Components/BasicTableViewCell/BasicTableViewCell.swift
  SafeUIKit/SafeUIKit/Components/BasicTableViewCell/BasicTableViewCell.xib
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
  safe/IdentityAccessImplementationsResources.bundle/_CodeSignature/CodeDirectory
  safe/IdentityAccessImplementationsResources.bundle/_CodeSignature/CodeRequirements-1
Labels: improvement

#813 Feature/gh 810 review recovery
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/RecoveryApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/WalletApplicationServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/EstimateTransactionRequest.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/MultiTokenEstimateTransactionRequest.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/TransactionRelayDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/MockTransactionRelayService1.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/TokenData+Token.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/Wallet.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/WalletDomainService.swift
  MultisigWallet/MultisigWalletImplementations/Services/HTTPGnosisTransactionRelayService.swift
  MultisigWallet/MultisigWalletImplementations/Services/MockTransactionRelayService.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinatorCreateOrRestoreTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreateSafe.storyboard
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreateSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreateSafeFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreationFeeIntro/CreationFeeIntroHeaderView.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreationFeeIntro/CreationFeeIntroHeaderView.xib
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreationFeeIntro/OnboardingCreationFeeIntroViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreationFeeIntro/OnboardingCreationFeeIntroViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreationFeeIntro/OnboardingPaymentMethodViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreationFeeIntro/OnboardingPaymentMethodViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreationProcessTracker.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/NewSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/OnboardingCreationFeeViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/OnboardingIntroViewController+CreateSafe.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/OnboardingIntroViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/OnboardingIntroViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/ConfirmMnemonicViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/ConfirmMnemonicViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/PaperWalletFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/PaperWalletFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/SaveMnemonicViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/SaveMnemonicViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ShadowWrapperView.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafe.storyboard
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafeViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafeViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/SafeCreationViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/NewSafeFlow/SafeCreationViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/OnboardingIntroViewController+RecoverSafe.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverRecoveryFeeViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/ReviewRecoveryTransactionViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/CardViewController/AddressDetailView.xib
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PaymentMethod/BasePaymentMethodViewController.swift
  SafeUIKit/SafeAppUI/UIAlertController+Safe.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeAppUI/generated/Sotryboards.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
  safe/IdentityAccessImplementationsResources.bundle/_CodeSignature/CodeDirectory
  safe/IdentityAccessImplementationsResources.bundle/_CodeSignature/CodeRequirements-1
Labels: improvement

#814 GH-812 payment method selection on manage BE screens
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/OwnerModificationApplicationService.swift
  MultisigWallet/MultisigWalletApplication/RBEStarter.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/ConnectBrowserExtensionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/ConnectBrowserExtensionDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/DisconnectBrowserExtensionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/DisconnectBrowserExtensionDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/RBETransactionMonitorEntry.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/RBETransactionMonitorRepository.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/ReplaceBrowserExtensionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/ReplaceBrowserExtensionDomainServiceBaseTestCase.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/ReplaceBrowserExtensionDomainServicePostProcessingTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/ReplaceBrowserExtensionDomainServiceSigningTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/ReplaceBrowserExtensionDomainServiceTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/RBEIntroViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/RBEIntroViewControllerActionsTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/RBEIntroViewControllerBaseTestCase.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/RBEIntroViewControllerErrorStateTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/RBEIntroViewControllerInvalidStateTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/RBEIntroViewControllerLoadingState.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/RBEIntroViewControllerLoadingStateTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/RBEIntroViewControllerReadyStateTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/RBEIntroViewControllerStartedStateTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/RBEIntroViewControllerStartingStateTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/RBEIntroViewControllerStateTransitionTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/RBEStarterMock.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/TestableRBEIntroViewController.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
Labels: feature

#820 GH-810 switched to working endpoint
  MultisigWallet/MultisigWalletApplication/RecoveryApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/MultiTokenEstimateTransactionRequest.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/MockTransactionRelayService1.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
  MultisigWallet/MultisigWalletImplementations/Services/HTTPGnosisTransactionRelayService.swift
  MultisigWallet/MultisigWalletImplementations/Services/MockTransactionRelayService.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverSafeFlowCoordinator.swift
Labels: improvement
