Repository gnosis/safe-ios, pull requests merged in 2019-11, with the labels that each got.

#1250 GH-1249 updated version
  CHANGELOG.rst
  safe/remoteNotificationHandler/Info.plist
  safe/safe/Info.plist
  safe/safe/Tests-Info.plist
  safe/safeUITests/Info.plist
Labels: maintenance

#1257 Feature/gh 1253 tooltip
  SafeUIKit/SafeAppUI/MainFlow/Tokens/ManageTokens/ManageTokensTableViewController.swift
  SafeUIKit/SafeUIKit/Components/FeedbackTooltip/FeedbackTooltip.swift
Labels: bug

#1258 GH-1256 enabled swipe back
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/SwitchSafesTableViewController.swift
Labels: bug

#1259 GH-1252 disabled deleting wallet entries
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookViewController.swift
Labels: bug

#1260 GH-1251 fixed
  Gemfile.lock
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/Wallet.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/WalletDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/WalletStates.swift
  MultisigWallet/MultisigWalletDomainModelTests/WalletTests.swift
  MultisigWallet/MultisigWalletImplementationsTests/DBAddressBookRepositoryTests.swift
  fastlane/Fastfile
Labels: bug

#1261 Feature/gh 1254 review label
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendReviewViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/TransactionDetails/TransactionDetailsViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransactionViewController.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/AccountBalanceView.swift
  SafeUIKit/SafeUIKit/Components/TransactionHeaderView/TransactionHeaderCell.swift
  SafeUIKit/SafeUIKit/Components/TransactionHeaderView/TransactionHeaderCellTests.swift
  SafeUIKit/SafeUIKit/Components/TransactionHeaderView/TransactionHeaderView.swift
  SafeUIKit/SafeUIKit/Components/TransactionHeaderView/TransactionHeaderView.xib
  SafeUIKit/SafeUIKit/Components/TransactionHeaderView/TransactionHeaderViewTests.swift
  SafeUIKit/SafeUIKit/Components/TransferView/SettingsTransactionHeaderView.swift
  SafeUIKit/SafeUIKitDemo/DetailControllers/TransactionHeaderViewController.swift
  SafeUIKit/SafeUIKitDemo/Main/Main.storyboard
Labels: bug

#1268 Feature/gh 1264 fix crash
  MultisigWallet/MultisigWalletApplication/EventRelay.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/mocks/MockWalletApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ErrorStream.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/EventPublisher.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/DBAddressBookRepository.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewController.swift
  safe/safe/AppDelegate.swift
Labels: bug

#1272 Release/1.9.0
  Gemfile.lock
  MultisigWallet/MultisigWalletApplication/EventRelay.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ErrorStream.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/EventPublisher.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/Wallet.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/WalletDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/WalletStates.swift
  MultisigWallet/MultisigWalletDomainModelTests/WalletTests.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/DBAddressBookRepository.swift
  MultisigWallet/MultisigWalletImplementationsTests/DBAddressBookRepositoryTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/SwitchSafesTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendReviewViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Tokens/ManageTokens/ManageTokensTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/TransactionDetails/TransactionDetailsViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransactionViewController.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/AccountBalanceView.swift
  SafeUIKit/SafeUIKit/Components/FeedbackTooltip/FeedbackTooltip.swift
  SafeUIKit/SafeUIKit/Components/TransactionHeaderView/TransactionHeaderCell.swift
  SafeUIKit/SafeUIKit/Components/TransactionHeaderView/TransactionHeaderCellTests.swift
  SafeUIKit/SafeUIKit/Components/TransactionHeaderView/TransactionHeaderView.swift
  SafeUIKit/SafeUIKit/Components/TransactionHeaderView/TransactionHeaderView.xib
  SafeUIKit/SafeUIKit/Components/TransactionHeaderView/TransactionHeaderViewTests.swift
  SafeUIKit/SafeUIKit/Components/TransferView/SettingsTransactionHeaderView.swift
  SafeUIKit/SafeUIKitDemo/DetailControllers/TransactionHeaderViewController.swift
  SafeUIKit/SafeUIKitDemo/Main/Main.storyboard
  fastlane/Fastfile
Labels: maintenance

#1288 Gh-1286 fixed the portfolio serialization issue
  MultisigWallet/MultisigWalletDomainModel/Portfolio/Portfolio.swift
  MultisigWallet/MultisigWalletDomainModelTests/PortfolioTests.swift
Labels: bug

#1291 GH-1273 added owners field
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletDomainModel/NotificationService/Messaging/CommunicationDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/NotificationService/Messaging/SafeCreatedMessage.swift
  MultisigWallet/MultisigWalletDomainModel/NotificationService/NotificationDomainService.swift
  MultisigWallet/MultisigWalletDomainModelTests/MessageTests.swift
  MultisigWallet/MultisigWalletDomainModelTests/MockNotificationService1.swift
  MultisigWallet/MultisigWalletImplementations/Services/HTTPNotificatonService.swift
  MultisigWallet/MultisigWalletImplementations/Services/MockNotificationService.swift
  safe/safe/IntegrationTests/HTTPNotificatonServiceTests.swift
Labels: improvement

#1292 GH-1290 fixed migration
  Common/CommonImplementations/TableSchema.swift
  safe/safe.xcodeproj/project.pbxproj
  safe/safe/Migrations/M0009_MigrateSafesNamesToAddressBook.swift
  safe/safe/Migrations/M0009_MigrateSafesNamesToAddressBookTests.swift
Labels: bug

#1306 GH-1305 updated
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/MainViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/SegmentBar.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/TransactionView/TransactionTableViewCell.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ConnectTwoFA/ConnectTwoFAFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ContractUpgrade/ContractUpgradeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/DisconnectTwoFA/DisconnectTwoFAFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/GetInTouch/GetInTouchTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceTwoFA/Intro/IntroContentView.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceTwoFA/ReplaceTwoFAFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WalletConnectFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreateSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/ConnectAuthenticatorSuccessViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/PairWith2FAController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/SeedIntroViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/SeedSuccessViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/TwoFATableViewCell.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/OnboardingFeePaidViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/OnboardingIntroViewController+RecoverSafe.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverFeePaidViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Tokens/BasicTableViewCell+TokenData.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/TwoFA/TwoFAView.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/Unlock/UnlockViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/Unlock/UnlockViewControllerTests.swift
  SafeUIKit/SafeAppUI/generated/Assets.swift
  SafeUIKit/SafeAppUI/generated/Colors.swift
  SafeUIKit/SafeAppUI/generated/Sotryboards.swift
  SafeUIKit/SafeAppUI/swiftgen.yml
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Components/AddressInput/AddressInput.swift
  SafeUIKit/SafeUIKit/Components/FeedbackTooltip/FeedbackTooltip.swift
  SafeUIKit/SafeUIKit/Components/StandardButton/StandardButton.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/TextInput/TextInput.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/VerifiableInput/RuleLabel.swift
  SafeUIKit/SafeUIKit/Components/ThreeStepsView/ThreeStepsView.swift
  SafeUIKit/SafeUIKit/Components/TokenInput/TokenInput.swift
  SafeUIKit/SafeUIKit/Components/TransactionConfirmationView/TransactionConfirmationView.swift
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/keycardConfirmation/keycard-confirmed.imageset/Contents.json
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/keycardConfirmation/keycard-confirmed.imageset/confirmed.pdf
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/keycardConfirmation/keycard-rejected.imageset/Contents.json
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/keycardConfirmation/keycard-rejected.imageset/rejected.pdf
  SafeUIKit/SafeUIKit/generated/Assets.swift
  SafeUIKit/SafeUIKit/generated/Colors.swift
  SafeUIKit/SafeUIKit/swiftgen.yml
  scripts/run_swiftgen_per_target.sh
Labels: maintenance

#1308 Feature/gh 1275 ens input screen
  AppConfig.example.yml
  Gemfile.lock
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/mocks/MockWalletApplicationService.swift
  MultisigWallet/MultisigWalletImplementations/Services/ENSAPIService.swift
  MultisigWallet/MultisigWalletImplementations/Services/IDN.swift
  MultisigWallet/MultisigWalletImplementations/en.lproj/Localizable.strings
  SafeUIKit/SafeAppUI/MainFlow/ENSInputViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Main.storyboard
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/MainTrackingEvents.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookEditEntryViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/AddressInputViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewController.swift
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/checkGreen.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/checkGreen.imageset/checkGreen.pdf
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeAppUI/generated/Assets.swift
  SafeUIKit/SafeAppUI/generated/Sotryboards.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Components/AddressInput/AddressInput.swift
  SafeUIKit/SafeUIKit/Components/AddressInput/AddressInputTests.swift
  SafeUIKit/SafeUIKit/Components/EthereumAddressLabel/FullEthereumAddressLabel.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/VerifiableInput/VerifiableInput.swift
  SafeUIKit/SafeUIKit/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKitDemo/DetailControllers/AddressInputViewController.swift
Labels: feature

#1312 GH-1277 opening of ens screen
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookEditEntryViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/AddressInputViewController.swift
Labels: feature

#1313 GH-1276 implemented reverse resolution
  MultisigWallet/MultisigWalletDomainModel/ENSContractProxy.swift
  MultisigWallet/MultisigWalletImplementations/Services/ENSAPIService.swift
  SafeUIKit/SafeAppUI/AddressResolvingViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookEntryViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/ReceiveFunds/ReceiveFundsViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/CardViewController/AddressDetailView.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/CardViewController/AddressDetailView.xib
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
Labels: feature

#1314 GH-1279 added new screen and removed old one
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceRecoveryPhrase/ReplaceRecoveryPhraseFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreateSafe.storyboard
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/PaperWalletFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/PaperWalletFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/SaveMnemonicViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/SaveMnemonicViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/SeedPhrase.storyboard
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/SeedWordCollectionViewCell.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/SeedWordCollectionViewCell.xib
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/ShowSeedViewController.swift
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/seed/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/seed/seed-badge-error.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/seed/seed-badge-error.imageset/seed-badge-error.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/seed/seed-badge-normal.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/seed/seed-badge-normal.imageset/seed-badge-normal.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/seed/seed-bg-empty.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/seed/seed-bg-empty.imageset/seed-bg-empty.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/seed/seed-bg-error.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/seed/seed-bg-error.imageset/seed-bg-error.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/seed/seed-bg-filled.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/seed/seed-bg-filled.imageset/seed-bg-filled.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/seed/seed-bg-normal.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/seed/seed-bg-normal.imageset/seed-bg-normal.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/seed/seed-input-normal.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/seed/seed-input-normal.imageset/seed-input-normal.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/seed/seed-input-selected.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/seed/seed-input-selected.imageset/seed-input-selected.pdf
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeAppUI/generated/Assets.swift
  SafeUIKit/SafeAppUI/generated/Sotryboards.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
Labels: feature

#1315 GH-1280 added new screen
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ChangePassword/SetupNewPasswordViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceRecoveryPhrase/ReplaceRecoveryPhraseFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreateSafe.storyboard
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/ConfirmMnemonicViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/ConfirmMnemonicViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/EnterSeed/EnterSeedViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/EnterSeed/InputSeedView.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/EnterSeed/SeedInputCollectionViewCell.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/EnterSeed/SeedInputCollectionViewCell.xib
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/EnterSeed/SeedPhrasePuzzle.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/EnterSeed/SeedPhrasePuzzleTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/PaperWalletFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/PaperWalletFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/SeedPhrase.storyboard
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/ShowSeed/SeedPhraseView.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/ShowSeed/SeedWord.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/ShowSeed/SeedWordCollectionViewCell.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/ShowSeed/SeedWordCollectionViewCell.xib
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/ShowSeed/ShowSeedViewController.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeAppUI/generated/Sotryboards.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/UIView+Pin.swift
Labels: feature

#1316 Feature/gh 1281 intro
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceRecoveryPhrase/ReplaceRecoveryPhraseFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceRecoveryPhrase/ReplaceRecoveryPhraseTrackingEvent.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/ReplaceSeedIntroViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/SeedPhrase.storyboard
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeAppUI/generated/Sotryboards.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
Labels: feature

#1317 GH-1284 Replaced paper wallet coordinator with seed flow controller
  SafeUIKit/SafeAppUI/FlowController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceRecoveryPhrase/ReplaceRecoveryPhraseFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreateSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreateSafeFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/PaperWalletFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/PaperWalletFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/SeedFlowController.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
Labels: improvement

#1320 Feature/gh 1311 send fee
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/mocks/MockWalletApplicationService.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ContractUpgrade/ContractUpgradeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/RemoveSafe/RemoveSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/RemoveSafe/RemoveSafeIntroViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/RemoveSafe/RemoveSafeIntroViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendInputViewModel.swift
Labels: bug

#1322 GH-1321 update version
  CHANGELOG.rst
  safe/remoteNotificationHandler/Info.plist
  safe/safe/Info.plist
  safe/safe/Tests-Info.plist
  safe/safeUITests/Info.plist
Labels: maintenance

#1324 GH-1323 showing screen on main thread
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/RemoveSafe/RemoveSafeIntroViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/EnterSeed/SeedPhrasePuzzle.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransactionViewController.swift
Labels: bug

#1326 GH-1325 fixed
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
Labels: bug
