Repository gnosis/safe-ios, pull requests merged in 2019-03, with the labels that each got.

#601 GH-598 and GH-599 back button edge cases
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/ConnectBrowserExtensionApplicationService.swift
  MultisigWallet/MultisigWalletApplication/ConnectBrowserExtensionApplicationServiceTests.swift
  MultisigWallet/MultisigWalletApplication/ReplaceBrowserExtensionApplicationService.swift
  MultisigWallet/MultisigWalletApplication/ReplaceBrowserExtensionApplicationServiceTests.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/Transaction/Transaction.swift
  MultisigWallet/MultisigWalletDomainModel/Transaction/TransactionStatus.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DisconnectBrowserExtensionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ReplaceBrowserExtensionDomainService.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PairWithBrowserExtension/PairWithBrowserExtensionViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/RecoveryPhraseInputViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransaction/ReviewTransactionViewController.swift
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
Labels: bug

#611 Feature/gh 522 bugs
  SafeUIKit/SafeAppUI/AppFlow/AppFlowCoordinator.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/StartViewController.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  safe/safe/AppDelegate.swift
  safe/safeUITests/SafeAppUI.strings
Labels: bug

#612 GH-607 added back timer instead of usleep
  Common/Database/SQLite/DataProtectionAwareCSQLite3.swift
  Common/Database/SQLite/FileSystemGuard.swift
Labels: bug

#622 GH-621 handling of the case when estimation for recovery phrase tx fails
  CHANGELOG.rst
  IdentityAccess/IdentityAccessImplementations/biometry/BiometricService.swift
  MultisigWallet/MultisigWalletApplication/RecoveryApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ConnectBrowserExtensionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DisconnectBrowserExtensionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ReplaceBrowserExtensionDomainService.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/MenuTableViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/Unlock/UnlockViewController.swift
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/unlock-screen/touch-id-icon.imageset/Contents.json
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  encrypted_files.tar.enc
Labels: bug

#624 Feature/gh 623
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/BaseWalletApplicationServiceTests.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/TokenListItemApplicationTests.swift
  MultisigWallet/MultisigWalletDomainModel/SynchronisationService/SynchronisationDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/Repeater.swift
  MultisigWallet/MultisigWalletImplementations/MockSynchronisationService.swift
  MultisigWallet/MultisigWalletImplementations/SynchronisationService.swift
  MultisigWallet/MultisigWalletImplementations/SynchronisationServiceTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/TokensTableViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/TokensTableViewControllerTests.swift
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
  safe/safe/AppDelegate.swift
  safe/safe/AppDelegateTests.swift
Labels: bug

#626 GH-625 fix bug
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/ManageTokens/ManageTokensTableViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/ManageTokens/ManageTokensTableViewControllerTests.swift
Labels: bug

#634 Release/1.1.0
  CHANGELOG.rst
  IdentityAccess/IdentityAccessImplementations/biometry/BiometricService.swift
  MultisigWallet/MultisigWalletApplication/RecoveryApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/BaseWalletApplicationServiceTests.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/TokenListItemApplicationTests.swift
  MultisigWallet/MultisigWalletDomainModel/SynchronisationService/SynchronisationDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ConnectBrowserExtensionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DisconnectBrowserExtensionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/MockSystem.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/Repeater.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ReplaceBrowserExtensionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/System.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/WalletStates.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/WalletTests.swift
  MultisigWallet/MultisigWalletImplementations/MockSynchronisationService.swift
  MultisigWallet/MultisigWalletImplementations/SynchronisationService.swift
  MultisigWallet/MultisigWalletImplementations/SynchronisationServiceTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/MenuTableViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/ManageTokens/ManageTokensTableViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/ManageTokens/ManageTokensTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/TokensTableViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Tokens/TokensTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/Unlock/UnlockViewController.swift
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/unlock-screen/touch-id-icon.imageset/Contents.json
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit/QRCodeScanner/ScannerViewController.xib
  encrypted_files.tar.enc
  safe/remoteNotificationHandler/Info.plist
  safe/safe/AppDelegate.swift
  safe/safe/AppDelegateTests.swift
  safe/safe/Info.plist
  safe/safe/Tests-Info.plist
  safe/safeUITests/Info.plist
Labels: maintenance

#635 GH-546 update icons
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.adhoc.appiconset/Contents.json
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.adhoc.appiconset/Rinkeby_staging_1024x1024.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.adhoc.appiconset/Rinkeby_staging_20x20_@2x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.adhoc.appiconset/Rinkeby_staging_20x20_@3x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.adhoc.appiconset/Rinkeby_staging_29x29_@2x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.adhoc.appiconset/Rinkeby_staging_29x29_@3x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.adhoc.appiconset/Rinkeby_staging_40x40_@2x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.adhoc.appiconset/Rinkeby_staging_40x40_@3x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.adhoc.appiconset/Rinkeby_staging_60x60_@2x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.adhoc.appiconset/Rinkeby_staging_60x60_@3x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.adhoc.appiconset/gnosis-adhoc-app-icon1024.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.adhoc.appiconset/gnosis-adhoc-app-icon20@2x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.adhoc.appiconset/gnosis-adhoc-app-icon20@3x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.adhoc.appiconset/gnosis-adhoc-app-icon29@2x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.adhoc.appiconset/gnosis-adhoc-app-icon29@3x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.adhoc.appiconset/gnosis-adhoc-app-icon40@2x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.adhoc.appiconset/gnosis-adhoc-app-icon40@3x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.adhoc.appiconset/gnosis-adhoc-app-icon60@2x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.adhoc.appiconset/gnosis-adhoc-app-icon60@3x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.dev.appiconset/AppIcon1024.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.dev.appiconset/AppIcon20@2x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.dev.appiconset/AppIcon20@3x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.dev.appiconset/AppIcon29@2x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.dev.appiconset/AppIcon29@3x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.dev.appiconset/AppIcon40@2x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.dev.appiconset/AppIcon40@3x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.dev.appiconset/AppIcon60@2x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.dev.appiconset/AppIcon60@3x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.dev.appiconset/Contents.json
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.dev.appiconset/Rinkeby_dev_1024x1024.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.dev.appiconset/Rinkeby_dev_20x20_@2x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.dev.appiconset/Rinkeby_dev_20x20_@3x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.dev.appiconset/Rinkeby_dev_29x29_@2x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.dev.appiconset/Rinkeby_dev_29x29_@3x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.dev.appiconset/Rinkeby_dev_40x40_@2x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.dev.appiconset/Rinkeby_dev_40x40_@3x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.dev.appiconset/Rinkeby_dev_60x60_@2x.png
  safe/safe/Assets.xcassets/AppIcon-io.gnosis.safe.dev.appiconset/Rinkeby_dev_60x60_@3x.png
Labels: improvement
