Repository gnosis/safe-ios, pull requests merged in 2019-02, with the labels that each got.

#536 GH-535 try out archiving
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
Labels: maintenance

#537 Feature/gh 532
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/MenuTableViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/MenuTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/FeatureFlagSettings.swift
  SafeUIKit/SafeAppUI/MenuCommand.swift
  SafeUIKit/SafeAppUI/ReplaceBrowserExtension/RBEFeatureFlag.swift
  SafeUIKit/SafeAppUI/ReplaceBrowserExtension/ReplaceBrowserExtensionCommand.swift
  SafeUIKit/SafeAppUI/ReplaceBrowserExtension/ReplaceBrowserExtensionFlowCoordinator.swift
  SafeUIKit/SafeAppUI/ReplaceBrowserExtension/ReplaceBrowserExtensionFlowCoordinatorTests.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  encrypted_files.tar.enc
  safe/safe.xcodeproj/project.pbxproj
  safe/safe/AppConfig.swift
  safe/safe/AppDelegate.swift
Labels: feature

#538 GH-531 new facade lib and resource bundle
  Common/Common.xcodeproj/project.pbxproj
  Common/ReplaceBrowserExtensionFacade/FeeCalculationError.swift
  Common/ReplaceBrowserExtensionFacade/Localizable.strings
  Common/ReplaceBrowserExtensionFacade/LocalizedString.swift
  Common/ReplaceBrowserExtensionFacade/RBEFeeCalculationData.swift
  Common/ReplaceBrowserExtensionFacade/RBEStarter.swift
  Common/ReplaceBrowserExtensionFacadeResources/Info.plist
  IdentityAccess/IdentityAccess.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/WalletSettingsApplicationService.swift
  SafeUIKit/ReplaceBrowserExtensionUI/RBEIntroViewController.swift
  SafeUIKit/ReplaceBrowserExtensionUI/RBEIntroViewControllerInvalidState.swift
  SafeUIKit/ReplaceBrowserExtensionUI/en.lproj/Localizable.strings
  SafeUIKit/ReplaceBrowserExtensionUITests/RBEIntroViewControllerErrorStateTests.swift
  SafeUIKit/ReplaceBrowserExtensionUITests/RBEIntroViewControllerInvalidStateTests.swift
  SafeUIKit/ReplaceBrowserExtensionUITests/RBEIntroViewControllerLoadingStateTests.swift
  SafeUIKit/ReplaceBrowserExtensionUITests/RBEIntroViewControllerReadyStateTests.swift
  SafeUIKit/ReplaceBrowserExtensionUITests/RBEIntroViewControllerStartingStateTests.swift
  SafeUIKit/ReplaceBrowserExtensionUITests/RBEStarterMock.swift
  SafeUIKit/SafeAppUI/Config.xcconfig
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/UIStaging/ViewController.swift
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
Labels: feature

#539 Feature/gh 531
  Common/Common.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/RecoveryApplicationService.swift
  MultisigWallet/MultisigWalletApplication/TransactionData.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/Transaction/Transaction.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ReplaceBrowserExtensionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ReplaceBrowserExtensionDomainServiceTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/TransactionDetails/TransactionDetailsViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/TransactionList/TransactionTableViewCell.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
Labels: feature

#549 Feature/ghi 541 connect extension
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/MockWalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/PairingWithBrowserExtensionTests.swift
  MultisigWallet/MultisigWalletApplication/WalletSettingsApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletSettingsApplicationServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/NotificationService/MockNotificationService.swift
  MultisigWallet/MultisigWalletDomainModel/NotificationService/NotificationDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/NotificationService/NotificationRequests/DeletePairRequest.swift
  MultisigWallet/MultisigWalletDomainModel/SafeOwnerManagerContractProxy.swift
  MultisigWallet/MultisigWalletDomainModel/SafeOwnerManagerContractProxyTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/MockNotificationService1.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ReplaceBrowserExtensionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ReplaceBrowserExtensionDomainServiceTests.swift
  MultisigWallet/MultisigWalletImplementations/HTTPNotificatonService.swift
  SafeUIKit/ReplaceBrowserExtensionUI/Common/FeeCalculation/FeeCalculationAssetLine+TextStyle.swift
  SafeUIKit/ReplaceBrowserExtensionUI/Common/FeeCalculation/FeeCalculationErrorLine.swift
  SafeUIKit/ReplaceBrowserExtensionUI/IntroContentView.swift
  SafeUIKit/ReplaceBrowserExtensionUI/RBEIntroViewController.swift
  SafeUIKit/ReplaceBrowserExtensionUI/RBEIntroViewControllerStartedState.swift
  SafeUIKit/ReplaceBrowserExtensionUI/en.lproj/Localizable.strings
  SafeUIKit/ReplaceBrowserExtensionUITests/RBEIntroViewControllerStartedStateTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/ConnectBrowserExtensionFlow/ConnectBrowserExtensionFlowCoordinator.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafeFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/RecoverSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/ReplaceBrowserExtension/PairWithBrowserExtensionViewController+RBE.swift
  SafeUIKit/SafeAppUI/ReplaceBrowserExtension/ReplaceBrowserExtensionCommand.swift
  SafeUIKit/SafeAppUI/ReplaceBrowserExtension/ReplaceBrowserExtensionFlowCoordinator.swift
  SafeUIKit/SafeAppUI/ReplaceBrowserExtension/ReplaceBrowserExtensionFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PairWithBrowserExtension/PairWithBrowserExtensionViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PairWithBrowserExtension/PairWithBrowserExtensionViewControllerTests.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/AttributedStringStyle.swift
  SafeUIKit/SafeUIKit/Base.lproj/Localizable.strings
  SafeUIKit/SafeUIKit/Components/LoadingTitleView/LoadingTitleView.swift
  SafeUIKit/SafeUIKit/Components/LoadingTitleView/LoadingTitleView.xib
  SafeUIKit/SafeUIKit/Components/ScanBarButtonItem/ScanBarButtonItem.swift
  SafeUIKit/SafeUIKit/Components/ScanBarButtonItem/ScanBarButtonItemTests.swift
  SafeUIKit/SafeUIKit/NibUIView.swift
  SafeUIKit/SafeUIKit/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKitDemo/DetailControllers/ScanButtonViewController.swift
  SafeUIKit/UIStaging/Base.lproj/Main.storyboard
  SafeUIKit/UIStaging/ConnectExtensionDemoViewController.swift
  SafeUIKit/UIStaging/Info.plist
  SafeUIKit/UIStaging/RBEIntroDemoViewController.swift
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
  safe/IdentityAccessImplementationsResources.bundle/_CodeSignature/CodeDirectory
  safe/IdentityAccessImplementationsResources.bundle/_CodeSignature/CodeRequirements-1
  safe/safe/IntegrationTests/HTTPNotificatonServiceTests.swift
Labels: feature

#551 Feature/ghi 543 phrase input
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/WalletSettingsApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletSettingsApplicationServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ReplaceBrowserExtensionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ReplaceBrowserExtensionDomainServiceBaseTestCase.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ReplaceBrowserExtensionDomainServiceSigningTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ReplaceBrowserExtensionDomainServiceTests.swift
  MultisigWallet/MultisigWalletImplementations/MockEncryptionService.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/RecoverSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/ReplaceBrowserExtension/ReplaceBrowserExtensionFlowCoordinator.swift
  SafeUIKit/SafeAppUI/ReplaceBrowserExtension/ReplaceBrowserExtensionFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/BaseInputViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/RecoveryPhraseInputViewController.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
Labels: feature

#557 GHI-542 added error alert to the camera
  SafeUIKit/SafeUIKit/Base.lproj/Localizable.strings
  SafeUIKit/SafeUIKit/Components/AddressInput/AddressInputTests.swift
  SafeUIKit/SafeUIKit/Components/QRCodeInput/QRCodeInputTests.swift
  SafeUIKit/SafeUIKit/QRCodeScanner/ScanQRCodeHandler.swift
  SafeUIKit/SafeUIKit/QRCodeScanner/ScanQRCodeHandlerTests.swift
  SafeUIKit/SafeUIKit/QRCodeScanner/ScannerViewController.swift
  SafeUIKit/SafeUIKit/QRCodeScanner/ScannerViewControllerTests.swift
  SafeUIKit/SafeUIKit/en.lproj/Localizable.strings
Labels: feature

#562 GH-561 improved
  Common/Common/Dispatch.swift
  MultisigWallet/MultisigWalletApplication/MockWalletApplicationService.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/NewSafeFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/PaperWalletSetupFlow/ConfirmMnemonicViewController.swift
  SafeUIKit/SafeAppUI/OnboardingFlow/SetupSafeFlow/NewSafeFlow/PaperWalletSetupFlow/ConfirmMnemonicViewControllerTests.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/Unlock/UnlockViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/Unlock/UnlockViewControllerTests.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/VerifiableInput/VerifiableInput.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/VerifiableInput/VerifiableInputTests.swift
  SafeUIKit/SafeUIKit/QRCodeScanner/ScanQRCodeHandler.swift
  SafeUIKit/SafeUIKit/QRCodeScanner/ScanQRCodeHandlerTests.swift
  SafeUIKit/SafeUIKit/QRCodeScanner/ScannerViewController.swift
  SafeUIKit/SafeUIKit/QRCodeScanner/ScannerViewControllerTests.swift
Labels: improvement

#560 Moved UIKit calls into a separate class
  Common/Database/SQLite/FileSystemGuard.swift
  safe/safe.xcodeproj/project.pbxproj
  safe/safe/AppDelegate.swift
  safe/safe/UIKitFileSystemGuard.swift
Labels: improvement

#554 Feature/gh 545 tx monitor
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/DomainRegistry.swift
  MultisigWallet/MultisigWalletDomainModel/NotificationService/Messaging/CommunicationDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RBETransactionMonitorEntry.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RBETransactionMonitorRepository.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ReplaceBrowserExtensionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ReplaceBrowserExtensionDomainServicePostProcessingTests.swift
  MultisigWallet/MultisigWalletImplementations/DBRBETransactionMonitorRepository.swift
  MultisigWallet/MultisigWalletImplementations/DBRBETransactionMonitorRepositoryIntegrationTests.swift
  MultisigWallet/MultisigWalletImplementations/SynchronisationService.swift
  safe/safe/AppDelegate.swift
Labels: feature

#566 Feature/ghi 544 rbe review transaction
  .env.default.example
  Gemfile.lock
  MultisigWallet/MultisigWalletApplication/MockWalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/BaseWalletApplicationServiceTests.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/SendTransactionTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MenuCommand.swift
  SafeUIKit/SafeAppUI/ReplaceBrowserExtension/ReplaceBrowserExtensionCommand.swift
  SafeUIKit/SafeAppUI/ReplaceBrowserExtension/ReplaceBrowserExtensionFlowCoordinator.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransaction/FundsTransfer/FundsTransferReviewTransactionViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransaction/FundsTransfer/FundsTransferReviewTransactionViewControllerTests.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransaction/ReplaceBrowserExtension/ReplaceBrowserExtensionReviewTransactionViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransaction/ReplaceRecoveryPhrase/ReplaceRecoveryPhraseReviewTransactionViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransaction/ReviewTransactionViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransaction/ReviewTransactionViewControllerTests.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/QRCodeScanner/ScannerViewControllerTests.swift
  SafeUIKit/UIStaging/ConnectExtensionDemoViewController.swift
  safe/remoteNotificationHandler/NotificationService.swift
Labels: feature

#581 Feature/gh 575
  MultisigWallet/MultisigWalletApplication/WalletSettingsApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletSettingsApplicationServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/NotificationService/Messaging/CommunicationDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ReplaceBrowserExtensionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ReplaceBrowserExtensionDomainServicePostProcessingTests.swift
  MultisigWallet/MultisigWalletImplementations/MockEncryptionService.swift
  SafeUIKit/ReplaceBrowserExtensionUI/RBEIntroViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/MenuTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/ConnectBrowserExtension/CBEFeatureFlag.swift
  SafeUIKit/SafeAppUI/ReplaceBrowserExtension/RBEFeatureFlag.swift
  SafeUIKit/SafeAppUI/ReplaceBrowserExtension/ReplaceBrowserExtensionCommand.swift
  SafeUIKit/SafeAppUI/ReplaceBrowserExtension/ReplaceBrowserExtensionFlowCoordinator.swift
  SafeUIKit/SafeAppUI/ReplaceBrowserExtension/ReplaceBrowserExtensionFlowCoordinatorTests.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/QRCodeScanner/ScannerViewController.swift
  SafeUIKit/SafeUIKit/QRCodeScanner/ScannerViewControllerTests.swift
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
Labels: feature

#582 Feature/gh 580
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/ConnectBrowserExtensionFlow/ConnectBrowserExtensionFlowCoordinator.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/ConnectBrowserExtensionFlow/ConnectBrowserExtensionFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/MainFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ConnectBrowserExtension/CBEFeatureFlag.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ConnectBrowserExtension/CBEIntroViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ConnectBrowserExtension/ConnectBrowserExtensionFlowCoordinator.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ConnectBrowserExtension/ConnectBrowserExtensionFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/PairWithBrowserExtensionViewController+RBE.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/ReplaceBrowserExtensionCommand.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/ReplaceBrowserExtensionFlowCoordinator.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/ReplaceBrowserExtensionFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/ReplaceBrowserExtensionReviewTransactionViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/TransactionSubmissionHandler.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
Labels: feature

#584 Feature/ghi 571 add extension command
  MultisigWallet/MultisigWalletDomainModel/Wallet/ReplaceBrowserExtensionDomainService.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ConnectBrowserExtensionLater/ConnectBrowserExtensionLaterCommand.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ConnectBrowserExtensionLater/ConnectBrowserExtensionLaterCommandTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/MenuTableViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/MenuTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
Labels: feature

#593 Feature/gh 576
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/ApplicationServiceRegistry.swift
  MultisigWallet/MultisigWalletApplication/ConnectBrowserExtensionApplicationService.swift
  MultisigWallet/MultisigWalletApplication/ConnectBrowserExtensionApplicationServiceTests.swift
  MultisigWallet/MultisigWalletApplication/FeeCalculationError.swift
  MultisigWallet/MultisigWalletApplication/Localizable.strings
  MultisigWallet/MultisigWalletApplication/OwnerModificationApplicationService.swift
  MultisigWallet/MultisigWalletApplication/RecoveryApplicationService.swift
  MultisigWallet/MultisigWalletApplication/ReplaceBrowserExtensionApplicationService.swift
  MultisigWallet/MultisigWalletApplication/ReplaceBrowserExtensionApplicationServiceTests.swift
  MultisigWallet/MultisigWalletApplication/TransactionData.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletSettingsApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/DomainRegistry.swift
  MultisigWallet/MultisigWalletDomainModel/SafeOwnerManagerContractProxy.swift
  MultisigWallet/MultisigWalletDomainModel/SafeOwnerManagerContractProxyTests.swift
  MultisigWallet/MultisigWalletDomainModel/Transaction/Transaction.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ConnectBrowserExtensionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ConnectBrowserExtensionDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ReplaceBrowserExtensionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ReplaceBrowserExtensionDomainServiceBaseTestCase.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ReplaceBrowserExtensionDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/TestableOwnerProxy.swift
  MultisigWallet/MultisigWalletImplementations/SynchronisationService.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ConnectBrowserExtension/CBEFeatureFlag.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ConnectBrowserExtension/CBEIntroViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ConnectBrowserExtension/ConnectBrowserExtensionFlowCoordinator.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ConnectBrowserExtension/ConnectBrowserExtensionFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ConnectBrowserExtension/ConnectBrowserExtensionLaterCommand.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ConnectBrowserExtension/ConnectBrowserExtensionLaterCommandTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ConnectBrowserExtensionLater/ConnectBrowserExtensionLaterCommandTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/MenuTableViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/MenuTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/Intro/IntroContentView.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/Intro/RBEIntroViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/Intro/RBEIntroViewController.xib
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/RBEReviewTransactionViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/ReplaceBrowserExtensionCommand.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/ReplaceBrowserExtensionFlowCoordinator.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/ReplaceBrowserExtensionFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/ReplaceBrowserExtensionReviewTransactionViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/TransactionDetails/TransactionDetailsViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/TransactionList/TransactionTableViewCell.swift
  SafeUIKit/SafeAppUI/MenuCommand.swift
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/connect-browser-extension/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/connect-browser-extension/connect-intro-icon.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/connect-browser-extension/connect-intro-icon.imageset/connect-intro-icon.pdf
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeAppUI/generated/Assets.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  safe/safe/AppDelegate.swift
Labels: feature

#595 Feature/gh 576 disconnect extension
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/ApplicationServiceRegistry.swift
  MultisigWallet/MultisigWalletApplication/DisconnectBrowserExtensionApplicationService.swift
  MultisigWallet/MultisigWalletApplication/FeeCalculationError.swift
  MultisigWallet/MultisigWalletApplication/Localizable.strings
  MultisigWallet/MultisigWalletApplication/OwnerModificationApplicationService.swift
  MultisigWallet/MultisigWalletApplication/RecoveryApplicationService.swift
  MultisigWallet/MultisigWalletApplication/TransactionData.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/DomainRegistry.swift
  MultisigWallet/MultisigWalletDomainModel/Transaction/Transaction.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ConnectBrowserExtensionDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DisconnectBrowserExtensionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DisconnectBrowserExtensionDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ReplaceBrowserExtensionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/TestableOwnerProxy.swift
  MultisigWallet/MultisigWalletImplementations/SynchronisationService.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ConnectBrowserExtension/ConnectBrowserExtensionFlowCoordinator.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ConnectBrowserExtension/ConnectBrowserExtensionFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/DisconnectBrowserExtension/DisconnectBrowserExtensionCommand.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/DisconnectBrowserExtension/DisconnectBrowserExtensionFlowCoordinator.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/MenuTableViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/MenuTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ReplaceBrowserExtension/ReplaceBrowserExtensionFlowCoordinator.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/TransactionDetails/TransactionDetailsViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/TransactionList/TransactionTableViewCell.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PairWithBrowserExtension/PairWithBrowserExtensionViewControllerTests.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  safe/safe/AppDelegate.swift
Labels: feature

#596 Feature/gh 450
  MultisigWallet/MultisigWalletApplication/WalletSettingsApplicationService.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/DisconnectBrowserExtension/DisconnectBrowserExtensionFlowCoordinator.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/MenuTableViewController.swift
  SafeUIKit/SafeAppUI/AppFlow/MainFlow/Menu/ResyncBrowserExtension/ResyncWithBrowserExtensionCommand.swift
  SafeUIKit/SafeAppUI/MenuCommand.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
Labels: feature
