Repository gnosis/safe-ios, pull requests merged in 2019-12, with the labels that each got.

#1330 Release/1.10.0
  CHANGELOG.rst
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/RemoveSafe/RemoveSafeIntroViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/SeedFlow/EnterSeed/SeedPhrasePuzzle.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransactionViewController.swift
  safe/remoteNotificationHandler/Info.plist
  safe/safe/Info.plist
  safe/safe/Tests-Info.plist
  safe/safeUITests/Info.plist
Labels: maintenance

#1331 GH-1329 replaced unowned with weak
  SafeUIKit/SafeAppUI/MainFlow/IncomingTransactionFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ChangePassword/ChangePasswordFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ConnectTwoFA/ConnectTwoFAFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/DisconnectTwoFA/DisconnectTwoFAFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceRecoveryPhrase/ReplaceRecoveryPhraseFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceTwoFA/ReplaceTwoFAFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreateSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Send/SendFlowCoordinator.swift
Labels: bug

#1344 GH-1343 added guard
  SafeUIKit/SafeAppUI/MainFlow/Menu/AddressBook/AddressBookEntryViewController.swift
Labels: bug

#1352 Feature/gh 1347 wc method
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/TransactionData.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletConnectApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/ERC20TokenContractProxy.swift
  MultisigWallet/MultisigWalletDomainModel/Transaction/Transaction.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/TransactionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/WalletConnect/WCMultiSendSubTransaction.swift
  MultisigWallet/MultisigWalletDomainModel/WalletConnect/WalletConnectDomainService.swift
  MultisigWallet/MultisigWalletDomainModelTests/TransactionDomainServiceTests.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectService.swift
  MultisigWallet/MultisigWalletImplementationsTests/WalletConnectServiceTests.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransactionViewController.swift
Labels: feature

#1361 GH-1360 updated version and changelog
  CHANGELOG.rst
  RELEASE.md
  safe/remoteNotificationHandler/Info.plist
  safe/safe/Info.plist
  safe/safe/Tests-Info.plist
  safe/safeUITests/Info.plist
Labels: maintenance

#1364 Feature/gh 1363 clipping fix
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/TransactionView/TransactionTableViewCell.xib
Labels: bug

#1365 Feature/gh 1362 decimal point token input
  SafeUIKit/SafeUIKit/Components/TokenInput/TokenInput.swift
  SafeUIKit/SafeUIKit/Components/TokenInput/TokenInputTests.swift
Labels: bug

#1369 Release/1.11.0 -> Master
  CHANGELOG.rst
  RELEASE.md
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/TransactionView/TransactionTableViewCell.xib
  SafeUIKit/SafeUIKit/Components/TokenInput/TokenInput.swift
  SafeUIKit/SafeUIKit/Components/TokenInput/TokenInputTests.swift
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/text inputs/password-hide-icon.imageset/Contents.json
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/text inputs/password-hide-icon.imageset/eye.pdf
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/text inputs/password-reveal-icon.imageset/Contents.json
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/text inputs/password-reveal-icon.imageset/eyeOff.pdf
  safe/remoteNotificationHandler/Info.plist
  safe/safe/Info.plist
  safe/safe/Tests-Info.plist
  safe/safeUITests/Info.plist
Labels: maintenance

#1379 Feature/gh 1357 new contract encoding
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/WalletConnectApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/EthereumContractProxy.swift
  MultisigWallet/MultisigWalletDomainModel/MultiSend/MultiSendContractProxy.swift
  MultisigWallet/MultisigWalletDomainModel/MultiSend/MultiSendContractV1.swift
  MultisigWallet/MultisigWalletDomainModel/MultiSend/MultiSendContractV2.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ContractModification/ContractUpgradeDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ContractModification/ReplaceRecoveryPhraseDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/SafeContractMetadata.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/SafeContractMetadataRepository.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/TransactionDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/WalletConnect/WCMultiSendSubTransaction.swift
  MultisigWallet/MultisigWalletDomainModelTests/BaseDeploymentDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModelTests/MultiSendContractProxyTests.swift
  MultisigWallet/MultisigWalletDomainModelTests/SafeCreationResponseValidatorTests.swift
  MultisigWallet/MultisigWalletDomainModelTests/TransactionDomainServiceTests.swift
  MultisigWallet/MultisigWalletImplementations/MockRepositories/MockSafeContractMetadataRepository.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/InMemorySafeContractMetadataRepository.swift
  MultisigWallet/MultisigWalletImplementationsTests/EncryptionServiceTests.swift
  encrypted_files.tar.enc
  info.plist
  safe/safe/AppConfig.swift
  safe/safe/IntegrationTests/HTTPGnosisTransactionRelayServiceTests.swift
Labels: feature, improvement

#1382 GH-1377 added notification processing
  safe/safe/AppDelegate.swift
  safe/safe/AppDelegateTests.swift
Labels: bug

#1385 Feature/gh 1384 bump version
  CHANGELOG.rst
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  safe/remoteNotificationHandler/Info.plist
  safe/safe/Info.plist
  safe/safe/Tests-Info.plist
  safe/safeUITests/Info.plist
Labels: maintenance

#1392 Feature/gh wc safe selection
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/PlaceholderCreator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCSelectSafeViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCTrackingEvent.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WalletConnectFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WalletConnectFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Components/BackgroundHeaderFooterView/BackgroundHeaderFooterView.swift
Labels: feature

#1393 GH-1338 add universal links support
  safe/safe/AppDelegate.swift
  safe/safe/safe.entitlements
Labels: feature

#1390 Feature/gh 1339 wc completion screen
  MultisigWallet/MultisigWalletApplication/WalletConnectApplicationService.swift
  MultisigWallet/MultisigWalletApplication/mocks/MockWalletConnectApplicationService.swift
  MultisigWallet/MultisigWalletApplicationTests/WalletConnectApplicationServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/WalletConnect/WalletConnectDomainService.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectService.swift
  SafeUIKit/SafeAppUI/MainFlow/IncomingTransactionFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCCompletionPanelViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCCompletionPanelViewController.xib
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCSessionListTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCTrackingEvent.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WalletConnectFlowCoordinator.swift
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/wc-completed.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/wc-completed.imageset/wc-logo.pdf
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeAppUI/generated/Assets.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
Labels: feature

#1394 feature/GH-1389-Remove-not-used-component-QRCodeInput.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Components/QRCodeInput/QRCodeInput.swift
  SafeUIKit/SafeUIKit/Components/QRCodeInput/QRCodeInputTests.swift
  SafeUIKit/SafeUIKitDemo/DetailControllers/QRCodeInputViewController.swift
  SafeUIKit/SafeUIKitDemo/Main/Main.storyboard
Labels: improvement

#1395 GH-1350 fixes touchid when multiple apps installed with the same product name
  safe/safe.xcodeproj/project.pbxproj
  safe/safe.xcodeproj/xcshareddata/xcschemes/remoteNotificationHandler.xcscheme
  safe/safe.xcodeproj/xcshareddata/xcschemes/safe.xcscheme
Labels: bug

#1397 GH-1396 release task
  CHANGELOG.rst
  Gemfile.lock
  safe/remoteNotificationHandler/Info.plist
  safe/safe/Info.plist
  safe/safe/Tests-Info.plist
  safe/safeUITests/Info.plist
Labels: maintenance

#1400 Feature/gh 1399 return fix
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCSessionListTableViewController.swift
  safe.xcworkspace/xcshareddata/xcschemes/IntegrationTests.xcscheme
Labels: bug
