Repository gnosis/safe-ios, pull requests merged in 2019-08, with the labels that each got.

#1033 GH-1031 use transaction block number to identify that a safe is alrea…
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/RelayRequests/GetSafeInfoRequest.swift
  MultisigWallet/MultisigWalletDomainModel/TransactionRelayService/TransactionRelayDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/MockTransactionRelayService1.swift
  MultisigWallet/MultisigWalletImplementations/Services/HTTPGnosisTransactionRelayService.swift
  MultisigWallet/MultisigWalletImplementations/Services/MockTransactionRelayService.swift
Labels: improvement

#1035 Feature/gh 1021 terms
  SafeUIKit/Colors.txt
  SafeUIKit/SafeAppUI/ErrorHandler.swift
  SafeUIKit/SafeAppUI/MainFlow/Main.storyboard
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/TransactionView/TransactionTableViewCell.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/TransactionView/TransactionViewViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCSendReviewViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreateSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/OnboardingCreationFeeViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/OnboardingIntroViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverRecoveryFeeViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/MasterPassword.storyboard
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/OnboardingTermsViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/ReceiveFunds/ReceiveFundsViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Tokens/ManageTokens/ManageTokensTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/TransactionDetails/TransactionDetailsViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/TransactionDetails/TransactionDetailsViewControllerTests.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/BaseInputViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/CardViewController/CardViewController.xib
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/RecoveryPhraseInputViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/TwoFA/TwoFAView.xib
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/TwoFA/TwoFAViewController.swift
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/no-results.imageset/emptyState.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/transaction-details/external_link.imageset/Contents.json
  SafeUIKit/SafeAppUI/UIAlertController+Safe.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeAppUI/generated/Colors.swift
  SafeUIKit/SafeUIKit/AttributedStringStyle.swift
  SafeUIKit/SafeUIKit/Components/FeeCalculation/FeeCalculationAssetLine.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/TextInput/TextInput.swift
  SafeUIKit/SafeUIKit/DashedSeparatorView.swift
  SafeUIKit/SafeUIKit/generated/Colors.swift
  SafeUIKit/SafeUIKitDemo/Main/Main.storyboard
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
Labels: improvement

#1037 Feature/gh 1021 buttons
  SafeUIKit/Colors.txt
  SafeUIKit/SafeAppUI/MainFlow/Main.storyboard
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/FeePaidViewController.xib
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/MasterPassword.storyboard
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/CardViewController/CardViewController.xib
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PaymentMethod/PaymentMethodFooterView.xib
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/unlock-screen/touch-id-icon.imageset/Contents.json
  SafeUIKit/SafeAppUI/generated/Colors.swift
  SafeUIKit/SafeUIKit/Components/StandardButton/StandardButton.swift
  SafeUIKit/SafeUIKit/Components/TransactionConfirmationView/TransactionConfirmationView.xib
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/bordered-button/Bordered_Inactive.imageset/Bordered_Inactive.pdf
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/bordered-button/Bordered_Inactive.imageset/Contents.json
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/bordered-button/Bordered_Normal.imageset/Bordered_Normal.pdf
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/bordered-button/Bordered_Normal.imageset/Contents.json
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/bordered-button/Bordered_Pressed.imageset/Bordered_Pressed.pdf
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/bordered-button/Bordered_Pressed.imageset/Contents.json
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/bordered-button/Contents.json
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/filled-button/Contents.json
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/filled-button/Filled_Inactive.imageset/Contents.json
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/filled-button/Filled_Inactive.imageset/Filled_Inactive.pdf
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/filled-button/Filled_Normal.imageset/Contents.json
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/filled-button/Filled_Normal.imageset/Filled_Normal.pdf
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/filled-button/Filled_Pressed.imageset/Contents.json
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/filled-button/Filled_Pressed.imageset/Filled_Pressed.pdf
  SafeUIKit/SafeUIKit/generated/Assets.swift
  SafeUIKit/SafeUIKit/generated/Colors.swift
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
Labels: improvement

#1038 Feature/gh 1021 textinput checkmark
  SafeUIKit/SafeAppUI/MainFlow/Menu/ChangePassword/SetupNewPasswordViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/VerifiableInput+Rules.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit/Components/TextInputs/VerifiableInput/RuleLabel.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/VerifiableInput/VerifiableInput.swift
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
Labels: improvement

#1039 GH-1021 adjusted alignment
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceBrowserExtension/Intro/IntroContentView.swift
Labels: improvement

#1043 GH-1022 get in touch & rate app
  MultisigWallet/MultisigWalletApplication/MockWalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/SystemInfo.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceConfiguration.swift
  MultisigWallet/MultisigWalletApplication/en.lproj/Localizable.strings
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/GetInTouch/GetInTouchCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/GetInTouch/GetInTouchTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/GetInTouch/GetInTouchTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/MenuTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/MenuTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/RateApp/RateAppCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/Support/AppVersionTableViewCell.swift
  SafeUIKit/SafeAppUI/MainFlow/MenuTrackingEvent.swift
  SafeUIKit/SafeAppUI/MainFlow/SupportFlowCoordinator.swift
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/get-in-touch/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/get-in-touch/gitter.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/get-in-touch/gitter.imageset/gitter.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/get-in-touch/mail.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/get-in-touch/mail.imageset/mailIOs.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/get-in-touch/telegram.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/get-in-touch/telegram.imageset/telegram.png
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/get-in-touch/telegram.imageset/telegram@2x.png
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/get-in-touch/telegram.imageset/telegram@3x.png
  SafeUIKit/SafeAppUI/UIAlertController+Safe.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeAppUI/generated/Assets.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Components/BasicTableViewCell/BasicTableViewCell.swift
  encrypted_files.tar.enc
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
  safe/safe/AppConfig.swift
Labels: feature

#1047 GH-1046 update changelog and version number
  CHANGELOG.rst
  safe/remoteNotificationHandler/Info.plist
  safe/safe/Info.plist
  safe/safe/Tests-Info.plist
  safe/safeUITests/Info.plist
Labels: maintenance

#1052 Feature/gh 1048
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceConfiguration.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/RateApp/RateAppCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/SupportFlowCoordinator.swift
  encrypted_files.tar.enc
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
  safe/IdentityAccessImplementationsResources.bundle/_CodeSignature/CodeDirectory
  safe/IdentityAccessImplementationsResources.bundle/_CodeSignature/CodeRequirements-1
  safe/safe/AppConfig.swift
Labels: feature

#1099 Release/1.5.0
  CHANGELOG.rst
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceConfiguration.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/RateApp/RateAppCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/SupportFlowCoordinator.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransactionViewController.swift
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/wallet-connect/1.imageset/onboarding1.pdf
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit/Components/StandardButton/StandardButton.swift
  encrypted_files.tar.enc
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
  safe/IdentityAccessImplementationsResources.bundle/_CodeSignature/CodeDirectory
  safe/IdentityAccessImplementationsResources.bundle/_CodeSignature/CodeRequirements-1
  safe/remoteNotificationHandler/Info.plist
  safe/safe/AppConfig.swift
  safe/safe/Info.plist
  safe/safe/Tests-Info.plist
  safe/safeUITests/Info.plist
Labels: maintenance

#1103 Feature/gh 1059
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/WalletApplicationServiceTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ContractUpgrade/ContractUpgradeCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ContractUpgrade/ContractUpgradeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ContractUpgrade/ContractUpgradeFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ContractUpgrade/ContractUpgradeTrackingEvent.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/MenuTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/Onboarding/OnboardingPageDataSource.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/Onboarding/OnboardingPageDataSourceTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/Onboarding/OnboardingStepViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/Onboarding/OnboardingStepViewController.xib
  SafeUIKit/SafeAppUI/MainFlow/Menu/Onboarding/OnboardingStepViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/Onboarding/OnboardingToolbar.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/Onboarding/OnboardingToolbarTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/Onboarding/OnboardingViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/Onboarding/OnboardingViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCOnboardingStepViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WalletConnectFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WalletConnectFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/SupportFlowCoordinator.swift
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/contract-upgrade/upgrade1.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/contract-upgrade/upgrade1.imageset/upgrade1.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/contract-upgrade/upgrade2.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/contract-upgrade/upgrade2.imageset/upgrade2.pdf
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/contract-upgrade/upgrade3.imageset/Contents.json
  SafeUIKit/SafeAppUI/SafeAppUIMedia.xcassets/contract-upgrade/upgrade3.imageset/upgrade3.pdf
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeAppUI/generated/Assets.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Components/StandardButton/StandardButton.swift
Labels: feature

#1105 Feature/gh 1060 contract intro
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/ApplicationServiceRegistry.swift
  MultisigWallet/MultisigWalletApplication/ContractUpgradeApplicationService.swift
  MultisigWallet/MultisigWalletApplication/MockWalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/RecoveryApplicationService.swift
  MultisigWallet/MultisigWalletApplication/TransactionData.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationServiceTests/WalletApplicationServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/DomainRegistry.swift
  MultisigWallet/MultisigWalletDomainModel/DomainRegistryTests.swift
  MultisigWallet/MultisigWalletDomainModel/Transaction/Transaction.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/ContractUpgradeDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/ContractUpgradeDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/SafeContractMetadataRepository.swift
  MultisigWallet/MultisigWalletDomainModel/WalletProxyContractProxy.swift
  MultisigWallet/MultisigWalletDomainModel/WalletProxyContractProxyTests.swift
  MultisigWallet/MultisigWalletImplementations/MockRepositories/MockSafeContractMetadataRepository.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/InMemorySafeContractMetadataRepository.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/InMemorySafeContractMetadataRepositoryTests.swift
  MultisigWallet/MultisigWalletImplementations/Services/EncryptionServiceTests.swift
  MultisigWallet/MultisigWalletImplementations/Services/SynchronisationService.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/MainTrackingEvents.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/TransactionView/TransactionTableViewCell.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ContractUpgrade/ContractUpgradeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ContractUpgrade/ContractUpgradeFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ContractUpgrade/ContractUpgradeTrackingEvent.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/MenuTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/MenuTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/Onboarding/OnboardingStepViewController.xib
  SafeUIKit/SafeAppUI/MainFlow/TransactionDetails/TransactionDetailsViewController.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  fastlane/Fastfile
  safe/safe/MultisigWalletConfigurator.swift
Labels: feature

#1107 Feature/gh 1057 main banner
  MultisigWallet/MultisigWalletApplication/ContractUpgradeApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/ContractUpgradeDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/ContractUpgradeDomainServiceTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Main.storyboard
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/HeaderScrollDelegate.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/MainBannerView.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/MainViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/MainViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ContractUpgrade/ContractUpgradeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/MenuTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/SafeTestCase.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
Labels: feature

#1109 Feature/gh 1064 cell height
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/AssetView/AssetViewViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/GetInTouch/GetInTouchTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCSendReviewViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCSessionListTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/PasswordViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Tokens/ManageTokens/AddTokenTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Tokens/ManageTokens/ManageTokensTableViewController.swift
  SafeUIKit/SafeAppUI/MenuCommand.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/PaymentMethod/BasePaymentMethodViewController.swift
  SafeUIKit/SafeUIKit/Components/BasicTableViewCell/BasicTableViewCell.swift
  SafeUIKit/SafeUIKit/Components/BasicTableViewCell/BasicTableViewCell.xib
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
Labels: bug

#1108 GH-1053 updated
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/PasswordViewController.swift
  safe/IdentityAccessImplementationsResources.bundle/Info.plist
Labels: bug

#1110 GH-1066 update error logging
  IdentityAccess/IdentityAccessImplementations/biometry/BiometricService.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/Unlock/UnlockViewController.swift
Labels: bug

#1115 Feature/gh 1015 wc fixes
  MultisigWallet/MultisigWalletApplication/WalletConnectApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/WalletConnect/WCSendTransactionRequest.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletConnectService.swift
Labels: bug

#1118 GH-1116 update new version to 1.6.0
  CHANGELOG.rst
  safe/remoteNotificationHandler/Info.plist
  safe/safe/Info.plist
  safe/safe/Tests-Info.plist
  safe/safeUITests/Info.plist
Labels: maintenance

#1121 GH-1120 shortcut contract upgrade
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/ContractUpgradeDomainService.swift
Labels: bug

#1124 GH-1123 fix networking problem
  MultisigWallet/MultisigWalletApplication/WalletConnectApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletConnectApplicationServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/WalletConnect/WalletConnectDomainService.swift
Labels: bug
