Repository gnosis/safe-ios, pull requests merged in 2019-09, with the labels that each got.

#1128 Release/1.6.0
  CHANGELOG.rst
  MultisigWallet/MultisigWalletDomainModel/Wallet/BrowserExtension/ContractUpgradeDomainService.swift
  safe/remoteNotificationHandler/Info.plist
  safe/safe/Info.plist
  safe/safe/Tests-Info.plist
  safe/safeUITests/Info.plist
Labels: maintenance

#1134 GH-1069 add new safe onboarding screens
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/Onboarding/OnboardingStepViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreateSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/OnboardingTrackingEvent.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit/AttributedStringStyle.swift
Labels: feature

#1135 GH-1070 implement three steps view
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Components/ThreeStepsView/ThreeStepsView.swift
  SafeUIKit/SafeUIKit/Components/ThreeStepsView/ThreeStepsView.xib
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/three-steps/Contents.json
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/three-steps/initial.imageset/Contents.json
  SafeUIKit/SafeUIKit/SafeUIKitMedia.xcassets/three-steps/initial.imageset/three-steps.png
  SafeUIKit/SafeUIKit/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit/generated/Assets.swift
  SafeUIKit/SafeUIKitDemo/DetailControllers/ThreeStepsViewController.swift
  SafeUIKit/SafeUIKitDemo/Main/Main.storyboard
Labels: feature

#1139 Feature/gh 1070 base step controller
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreateSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/HeaderImageTextStepController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/HeaderImageTextView.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/HeaderImageTextView.xib
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/NewSafeThreeStepsBaseController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/PairWith2FAController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/ThreeStepsToSecurityController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/ThreeStepsToSecurityView.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/ThreeStepsToSecurityView.xib
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/OnboardingTrackingEvent.swift
  SafeUIKit/SafeAppUI/MainFlow/UIBarButtonItem+Items.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
  SafeUIKit/SafeUIKit/Components/ThreeStepsView/ThreeStepsView.xib
  SafeUIKit/SafeUIKitDemo/Main/Main.storyboard
Labels: feature

#1148 GH-1085 recovery flow
  MultisigWallet/MultisigWalletApplication/KeycardApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreateSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/NewSafeThreeStepsBaseController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/StatusKeycard/SKKeycardFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/StatusKeycard/SKPairingSuccessViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverSafeFlowCoordinator.swift
  safe/safe/Info.plist
Labels: feature

#1152 GH-1104 fixing
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ReplaceRecoveryPhraseDomainService.swift
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/MainViewController.swift
Labels: bug

#1155 Feature/gh 1087 keycard stauts refactoring
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/ContractModification/ConnectTwoFAApplicationService.swift
  MultisigWallet/MultisigWalletApplication/ContractModification/ContractUpgradeApplicationService.swift
  MultisigWallet/MultisigWalletApplication/ContractModification/DisconnectTwoFAApplicationService.swift
  MultisigWallet/MultisigWalletApplication/ContractModification/OwnerModificationApplicationService.swift
  MultisigWallet/MultisigWalletApplication/ContractModification/ReplaceRecoveryPhraseApplicationService.swift
  MultisigWallet/MultisigWalletApplication/ContractModification/ReplaceTwoFAApplicationService.swift
  MultisigWallet/MultisigWalletApplication/KeycardApplicationService.swift
  MultisigWallet/MultisigWalletApplication/RecoveryApplicationService.swift
  MultisigWallet/MultisigWalletApplication/TransactionData.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/mocks/MockEthereumApplicationService.swift
  MultisigWallet/MultisigWalletApplication/mocks/MockRecoveryApplicationService.swift
  MultisigWallet/MultisigWalletApplication/mocks/MockWalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/mocks/MockWalletConnectApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/Transaction/Transaction.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ContractModification/ConnectTwoFADomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ContractModification/ContractUpgradeDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ContractModification/ContractUpgradeDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ContractModification/DisconnectTwoFADomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ContractModification/RBETransactionMonitorEntry.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ContractModification/RBETransactionMonitorRepository.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ContractModification/ReplaceRecoveryPhraseDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ContractModification/ReplaceTwoFADomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/Wallet.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/WalletDiagnositcDomainService.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ConnectTwoFA/ConnectTwoFAFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ContractUpgrade/ContractUpgradeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/DisconnectTwoFA/DisconnectTwoFAFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceTwoFA/ReplaceTwoFAFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreateSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/StatusKeycard/SKActivateViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/StatusKeycard/SKKeycardFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/StatusKeycard/SKPairViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/StatusKeycard/SKPairingSuccessViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransactionViewController.swift
Labels: bug

#1157 Feature/gh 1154 bugs
  SafeUIKit/SafeAppUI/MainFlow/MainScreen/TransactionView/TransactionTableViewCell.swift
  SafeUIKit/SafeAppUI/MainFlow/Tokens/ManageTokens/AddTokenTableViewController.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit/Components/BasicTableViewCell/BasicTableViewCell.swift
  SafeUIKit/SafeUIKit/Components/BasicTableViewCell/BasicTableViewCell.xib
Labels: bug

#1158 Feature/gh 1154 text input
  SafeUIKit/SafeAppUI/ErrorHandler.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ChangePassword/ChangePasswordFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/StatusKeycard/SKKeycardFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/PasswordViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransactionViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/TwoFA/AuthenticatorViewController.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/Unlock/UnlockViewController.swift
  SafeUIKit/SafeUIKit/Components/AddressInput/AddressInput.swift
  SafeUIKit/SafeUIKit/Components/TextInputs/TextInput/TextInput.swift
  SafeUIKit/SafeUIKitDemo/DetailControllers/TextInputViewController.swift
  safe/safe/IdentityAccessConfigurator.swift
  safe/safe/MultisigWalletConfigurator.swift
Labels: bug

#1159 GH-1144 is available check
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WalletConnectFlowCoordinator.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
Labels: bug

#1160 GH-1136 changed diagnostics
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/DomainRegistry.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/WalletDiagnosticService.swift
  MultisigWallet/MultisigWalletImplementations/Services/WalletDiagnosticDomainService.swift
  safe/safe/MultisigWalletConfigurator.swift
Labels: bug

#1161 GH-1154 fix unit tests
  IdentityAccess/IdentityAccessApplication/MockAuthenticationService.swift
  MultisigWallet/MultisigWalletApplication/WalletSettingsApplicationService.swift
  MultisigWallet/MultisigWalletApplication/mocks/MockWalletConnectApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/NotificationService/Messaging/CommunicationDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ContractModification/ConnectTwoFADomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ContractModification/ContractUpgradeDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/ContractModification/ReplaceTwoFADomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
  MultisigWallet/MultisigWalletDomainModelTests/ConnectTwoFADomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModelTests/DisconnectTwoFADomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModelTests/ReplaceTwoFADomainServicePostProcessingTests.swift
  SafeUIKit/SafeAppUI/ErrorHandler.swift
  SafeUIKit/SafeAppUI/ErrorHandlerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ChangePassword/ChangePasswordFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/DisconnectTwoFA/DisconnectTwoFAFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreateSafeFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/Welcome/PasswordViewControllerTests.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/ReviewTransactionViewControllerTests.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/Unlock/UnlockViewControllerTests.swift
  SafeUIKit/SafeAppUI/TestExtensions.swift
Labels: maintenance

#1162 Feature/gh 1154 localizations
  SafeUIKit/SafeAppUI/MainFlow/Menu/ConnectTwoFA/ConnectTwoFACommand.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ConnectTwoFA/ConnectTwoFAFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/DisconnectTwoFA/DisconnectTwoFACommand.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/DisconnectTwoFA/DisconnectTwoFAFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceTwoFA/ReplaceTwoFACommand.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceTwoFA/ReplaceTwoFAFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/StatusKeycard/SKActivateViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/StatusKeycard/SKIntroViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/StatusKeycard/SKKeycardFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/StatusKeycard/SKPairViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/StatusKeycard/SKPairingSuccessViewController.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
Labels: bug

#1164 GH-1163 updated version and changelog
  CHANGELOG.rst
  safe/remoteNotificationHandler/Info.plist
  safe/safe/Info.plist
  safe/safe/Tests-Info.plist
  safe/safeUITests/Info.plist
Labels: maintenance

#1169 Feature/gh 1088 select safe
  .gitignore
  Common/Common.xcodeproj/project.pbxproj
  Common/Common/WalletData.swift
  MultisigWallet/MultisigWallet.xcodeproj/project.pbxproj
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplicationTests/MultisigWalletApplicationTests.swift
  MultisigWallet/MultisigWalletApplicationTests/ReplaceTwoFAApplicationServiceTests.swift
  MultisigWallet/MultisigWalletApplicationTests/WalletApplicationServiceTests/BaseWalletApplicationServiceTests.swift
  MultisigWallet/MultisigWalletApplicationTests/WalletApplicationServiceTests/PairingWithBrowserExtensionTests.swift
  MultisigWallet/MultisigWalletApplicationTests/WalletApplicationServiceTests/SendTransactionTests.swift
  MultisigWallet/MultisigWalletApplicationTests/WalletApplicationServiceTests/TokenListItemApplicationTests.swift
  MultisigWallet/MultisigWalletApplicationTests/WalletApplicationServiceTests/WalletApplicationServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Ethereum/Token/TokenListItemRepository.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/WalletData+Wallet.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/WalletStates.swift
  SafeUIKit/SafeAppUI/MainFlow/Main.storyboard
  SafeUIKit/SafeAppUI/MainFlow/Menu/MenuTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/MenuTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SelectSafe/SafeTableViewCell.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SelectSafe/SafeTableViewCellTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/SwitchSafesCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/SwitchSafesFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/SwitchSafesTableViewCell.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/SwitchSafesTableViewCell.xib
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/SwitchSafesTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/WalletConnect/WCSessionListCell.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
Labels: feature

#1170 GH-1094 Extended deployment domain service for multiple wallets
  MultisigWallet/CommonTests/InMemoryWalletRepository.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/WalletRepository.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/WalletStates.swift
  MultisigWallet/MultisigWalletDomainModelTests/AllDeploymentStatesTests.swift
  MultisigWallet/MultisigWalletDomainModelTests/BaseDeploymentDomainServiceTests.swift
  MultisigWallet/MultisigWalletDomainModelTests/DeploymentDomainServiceTests.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/DBWalletRepository.swift
  MultisigWallet/MultisigWalletImplementationsTests/DBWalletRepositoryIntegrationTests.swift
Labels: feature

#1171 GH-1094 Added clean up of draft safes
  MultisigWallet/CommonTests/InMemoryAccountRepository.swift
  MultisigWallet/CommonTests/InMemoryTransactionRepository.swift
  MultisigWallet/MultisigWalletApplication/WCPendingTransactionsRepository.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/mocks/MockWalletApplicationService.swift
  MultisigWallet/MultisigWalletApplicationTests/WalletApplicationServiceTests/BaseWalletApplicationServiceTests.swift
  MultisigWallet/MultisigWalletApplicationTests/WalletApplicationServiceTests/WalletApplicationServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Account/AccountRepository.swift
  MultisigWallet/MultisigWalletDomainModel/Portfolio/Portfolio.swift
  MultisigWallet/MultisigWalletDomainModel/Transaction/TransactionRepository.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainService.swift
  MultisigWallet/MultisigWalletDomainModelTests/PortfolioTests.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/DBAccountRepository.swift
  MultisigWallet/MultisigWalletImplementations/Repositories/DBTransactionRepository.swift
  MultisigWallet/MultisigWalletImplementationsTests/DBAccountRepositoryIntegrationTests.swift
  MultisigWallet/MultisigWalletImplementationsTests/DBTransactionRepositoryTests.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/MenuTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreateSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/OnboardingCreateOrRestoreViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/OnboardingCreateOrRestoreViewControllerTests.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/Onboarding/OnboardingViewController.swift
Labels: feature

#1173 create safe menu item
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplication/mocks/MockWalletApplicationService.swift
  MultisigWallet/MultisigWalletDomainModel/Account/AccountUpdateDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/DomainRegistry.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/DeploymentDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/WalletStates.swift
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/MenuTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreateSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/OnboardingCreationFeeViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/CreateSafeCommand.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
Labels: feature

#1176 Feature/gh 1089 remove safe enter seed
  MultisigWallet/MultisigWalletApplication/RecoveryApplicationService.swift
  MultisigWallet/MultisigWalletApplication/WalletApplicationService.swift
  MultisigWallet/MultisigWalletApplicationTests/WalletApplicationServiceTests/WalletApplicationServiceTests.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/RecoveryDomainService.swift
  MultisigWallet/MultisigWalletDomainModel/Wallet/WalletData+Wallet.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/RemoveSafe/RemoveSafeEnterSeedViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/RemoveSafe/RemoveSafeEnterSeedViewControllerTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/RemoveSafe/RemoveSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/RemoveSafe/RemoveSafeFlowCoordinatorTests.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/SwitchSafesCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/SwitchSafesFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/SwitchSafesTableViewCell.xib
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/BaseAddSafeCommand.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/BaseInputViewController.swift
  SafeUIKit/SafeUIKit.xcodeproj/project.pbxproj
Labels: feature

#1177 Feature/gh 1089 remove safe finish
  SafeUIKit/SafeAppUI/MainFlow/MainFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ChangePassword/ChangePasswordCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ConnectTwoFA/ConnectTwoFACommand.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ConnectTwoFA/ConnectTwoFAFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/FeePaymentMethod/FeePaymentMethodCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/GetInTouch/GetInTouchCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/MenuTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/Portfolio/ManageTokensCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/RateApp/RateAppCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceTwoFA/ReplaceTwoFACommand.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ReplaceTwoFA/ReplaceTwoFAFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/ResyncBrowserExtension/ResyncWithBrowserExtensionCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/Support/LicensesCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/Support/PrivacyPolicyCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/Support/TermsCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/RemoveSafe/RemoveSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/SwitchSafes/SwitchSafesCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/BaseAddSafeCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/CreateSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/CreateSafeCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/CreateSafe/ThreeSteps/StatusKeycard/SKKeycardFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverSafe.storyboard
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverSafeCommand.swift
  SafeUIKit/SafeAppUI/MainFlow/OnboardingFlow/SetupSafeFlow/RecoverSafe/RecoverSafeFlowCoordinator.swift
  SafeUIKit/SafeAppUI/MenuCommand.swift
  SafeUIKit/SafeAppUI/ReusableDetachedControllers/RecoveryPhraseInputViewController.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
  safe/safe/AppDelegate.swift
Labels: feature

#1182 GH-1092 update Menu
  MultisigWallet/MultisigWalletApplication/mocks/MockWalletApplicationService.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/MenuTableViewController.swift
  SafeUIKit/SafeAppUI/MainFlow/Menu/MenuTableViewControllerTests.swift
  SafeUIKit/SafeAppUI/en.lproj/Localizable.strings
Labels: feature
